<p>
    <?php printf($this->translate('Hello!'))?>, <br>
    <br>
    <?php printf($this->translate('This email informs that your <a href="%s">Trendmed.eu</a> account has a new password.', $_SERVER['HTTP_HOST'] ))?><br>
    <br>
    <?php printf($this->translate('If You have not change your password and yet you have recieved this message, please  <a href="http://%s">contact the administration</a>.', $_SERVER['HTTP_HOST'].$this->url(array('type' => "feedback"), 'contact') ))?><br>
    <br>
    <?php printf($this->translate('Regards'))?>, <br>
    <?php printf($this->translate('Trendmed.eu Team'))?><br>
    <br>
    <br>
    <?php printf($this->translate('If you require any further information please do not hesitate <a href="http://%s">to contact us.</a>', $_SERVER['HTTP_HOST'].$this->url(array('type' => "feedback"), 'contact')))?><br>
    <a href="http://<?= $_SERVER['HTTP_HOST'];?>"><img src="<?= $_SERVER['HTTP_HOST'];?>/img/logo.png" /></a>
</p>