<!DOCTYPE html>
<html lang="pl">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" >
</head>
<body>
<p>
    Dzień Dobry,<br>
    ten e-mail informuję o zmianie hasła do Twojego konta na profilu <a href="http://www.trendmed.eu">Trendmed.eu</a>.
</p>
<p>
    Od teraz możesz składać rezerwacje w klinikach.
    <a href="http://www.trendmed.eu/clinic">http://www.trendmed.eu/clinic</a>
</p>
<footer>
    Zespół Trendmed
</footer>
</body>
</html>
