<p>
    Witamy na portalu Trendmed.eu!<br>
    <br>
    Właśnie dokonałeś pełnej aktywacji konta. Masz teraz nieograniczony dostęp do katalogu usług medycznych, kosmetycznych, sanatoriów czy spa-weelness. Możesz online rezerwować wybrane usługi bez potrzeby osobistego kontaktu i zbędnych formalności! 
    Pozdrawiamy<br>
    Zespół Trendmed<br>
    <br>
    <br>
    Jeśli masz jakiekolwiek pytania dotyczące funkcjonowania portalu <a href="http://<?= $_SERVER['HTTP_HOST'];?><?= $this->url(array('type' => "feedback"), 'contact'); ?>">skontaktuj się z nami</a>. <br>
</p>