<p>
    <?php printf($this->translate('Welcome to Trendmed.eu!'))?><br>
    <br>
    <br>
    <?php printf ($this->translate('You have just activated your account. From now on You have unlimited access to medical services, beauty parlours and spa centres. You can book all these services without going out of Your home and without all complicated formalities <a href="http://%s">Log in and book Your service now!</a>', $_SERVER['HTTP_HOST'].$this->url(array('module' => 'patient', 'controller'=> 'index'), 'default' ))) ?><br>
</p>
<?= $this->render('reservationNotifications/patient/_patientEmailFooter.phtml'); ?>