<?= $this->page->content; ?>
<? if($this->LoggedUser()->role->name == 'admin'): ?>
    <a href="<?= $this->url(array('action' => 'save-page', 'controller' => 'pages', 'module' => 'admin', 'id' => $this->page->id), 'default', true); ?>"><?= $this->translate("Edit page"); ?></a>
<? endif; ?>
<? if($this->page->type == 'Article' or $this->page->type == 'Camera review'): ?>
    <?= $this->Like($this->page); ?>
<? endif; ?>
