<div class="hero-unit">
    <h1>Zapraszamy do rejestracji</h1>

    <p>Zapraszamy placówki do rejestracji już teraz.
        Dzięki temu, po premierze serwisu uzyskasz atrakcyjne rabaty i aż 3 miesiące
        abonamentu gratis.</p>

    <p><a class="btn btn-primary btn-large" href="<?= $this->url(array(
        'action' => 'index',
        'controller' => 'register',
        'module' => 'clinic',
    ), 'default', true); ?>">Przejdź do rejestracji &raquo;</a>

        <a class="btn btn-primary" href="<?= $this->url(array(
            'action' => 'index',
            'controller' => 'index',
            'module' => 'clinic',
        ), 'default', true); ?>">Logowanie &raquo;</a></p>
</div>
<div class="hero-unit">
    <h1>Dowiedz się więcej</h1>

    <p>Więcej na temat tego czym jest <strong>Trendmed</strong> możesz dowiedzieć się z naszej prezentacji. </p>

    <p><a class="btn btn-primary btn-large" href="http://www.trendmed.eu/prezentacja/trendmed.pdf">Pobierz
        PDF &raquo;</a></p>
</div>
<!-- NAJWNOSZE KLINIKI @todo ostylować -->
<?php if (count($this->newClinics) > 0): ?>
    <h1><?= $this->translate('Last added clinics'); ?></h1>
<?php foreach ($this->newClinics as $clinic): ?>
    <h2><?= $clinic->name; ?></h2>
    <?= $this->ShowClinicLogo($clinic, 'small'); ?>

    <a href="<?= $this->url(
        array('slug' => $clinic->getSlug()), 'clinic', true
    ); ?>"><?= $this->translate('See profile'); ?></a>
    <?php endforeach; ?>
<?php endif; ?>
<!-- @todo ostylować -->
<?php if (count($this->articles) > 0): ?>
<?php foreach ($this->articles as $article): ?>
    <h2><?= $article->getTitle(); ?></h2>
    <?php if ($article->getLeadPhoto()): ?>
            <?=
            $this->ShowPhoto($article->getLeadPhoto(), 'small', 'ArticlePhoto')
            ; ?>
        <?php endif; ?>
        <?=
        $this->Truncate($article->content)->toLength(100)
        ; ?>

    <a href="<?= $this->url(
        array('slug' => $article->getSlug()), 'page', true
    ); ?>"><?= $this->translate('Read more'); ?></a>
    <?php endforeach; ?>
<?php endif; ?>