<div class="hero-unit">
    <h1>Zapraszamy do rejestracji</h1>

    <p>Zapraszamy placówki do rejestracji już teraz.
        Dzięki temu, po premierze serwisu uzyskasz atrakcyjne rabaty i aż 3 miesiące
        abonamentu gratis.</p>

    <p><a class="btn btn-primary btn-large" href="<?= $this->url(array(
        'action' => 'index',
        'controller' => 'register',
        'module' => 'clinic',
    ), 'default', true); ?>">Przejdź do rejestracji &raquo;</a>

        <a class="btn btn-primary" href="<?= $this->url(array(
            'action' => 'index',
            'controller' => 'index',
            'module' => 'clinic',
        ), 'default', true); ?>">Logowanie &raquo;</a></p>
</div>
<div class="hero-unit">
    <h1>Dowiedz się więcej</h1>

    <p>Więcej na temat tego czym jest <strong>Trendmed</strong> możesz dowiedzieć się z naszej prezentacji. </p>

    <p><a class="btn btn-primary btn-large" href="http://www.trendmed.eu/prezentacja/trendmed.pdf">Pobierz
        PDF &raquo;</a></p>
</div>

<!-- @todo ostylować -->
<?php if (count($this->articles) > 0): ?>
<div class="hero-unit articles">
	<h1 class="pull-left"><?= $this->translate('Latest articles'); ?>:</h1>
	<a class="btn btn-primary btn-large pull-right" href="<?= $this->url(array(
        'action' => 'archive',
        'controller' => 'pages',
        'module' => 'default'
    ), 'default', true); ?>"><?= $this->translate('Show all articles'); ?></a>
	<div class="clearfix"></div>

		<div class="row-fluid">
			<div class="span6">
				<div class="lead-article">
					<?php if ($this->articles[0]->getLeadPhoto()): ?>
						<?= $this->ShowPhoto($this->articles[0]->getLeadPhoto(), 'big', 'ArticlePhoto'); ?>
					<?php endif; ?>
					<div class="lead-article-content">
						<div class="lead-article-content-inner">
							<a href="<?= $this->url(
							   	array('slug' => $this->articles[0]->getSlug()), 'page', true
							    ); ?>"><h2><?= $this->articles[0]->getTitle(); ?></h2>
							<?= $this->articles[0]->content; ?></a>
						</div>
					</div>
				</div>
			</div>
			<div class="span6">
				<div class="other-articles">
                <?php if (!empty($this->articles[1])): ?>
                    <div class="row-fluid">
						<div class="span4">
							 <?php if ($this->articles[1]->getLeadPhoto()): ?>
							 	<?= $this->ShowPhoto($this->articles[1]->getLeadPhoto(), 'medium', 'ArticlePhoto'); ?>
							 <?php endif; ?>
						</div>
						<div class="span8">
							 <a href="<?= $this->url(
						        array('slug' => $this->articles[1]->getSlug()), 'page', true
						    ); ?>"><h2><?= $this->articles[1]->getTitle(); ?></h2></a>
							 <a href="<?= $this->url(
						        array('slug' => $this->articles[1]->getSlug()), 'page', true
						    ); ?>" class="read-more"><?= $this->translate('Read more'); ?></a>
						</div>
					</div>
					<div class="clear"></div>
                <?php endif; ?>
                <?php if (!empty($this->articles[2])): ?>

                    <div class="row-fluid">
						<div class="span4">
					 		<?php if ($this->articles[2]->getLeadPhoto()): ?>
							 	<?= $this->ShowPhoto($this->articles[2]->getLeadPhoto(), 'medium', 'ArticlePhoto'); ?>
							 <?php endif; ?>
						</div>
						<div class="span8">
							 <a href="<?= $this->url(
					    	    array('slug' => $this->articles[2]->getSlug()), 'page', true
					    	); ?>"><h2><?= $this->articles[2]->getTitle(); ?></h2></a>
							 <a href="<?= $this->url(
					    	    array('slug' => $this->articles[2]->getSlug()), 'page', true
					    	); ?>" class="read-more"><?= $this->translate('Read more'); ?></a>
						</div>
					</div>
                <?php endif; ?>
				</div>
			</div>
		</div>
</div>
<?php endif; ?>


<!-- @todo ostylować usługi -->
<?php if (count($this->newServices) > 0): ?>
<div class="hero-unit">
	<h1><?= $this->translate('Last added services'); ?>:</h1>
	<div class="row-fluid grid-list">
		<?php foreach ($this->newServices as $service): ?>
		<div class="span4 grid-list-item">
			<a href="<?= $this->url(
    		    array('id' => $service->id), 'service', true
    		); ?>"><div class="crop"><?= $this->ShowPhoto($service->photos[0], 'small', 'services'); ?></div></a>
    		
    		<div class="grid-desc">
	   			<a href="<?= $this->url(
	    		    array('id' => $service->id), 'service', true
	    		); ?>"><h2><?= $service->category->name; ?></h2></a>
				<p class="price"><?= $this->translate('From'); ?> <span><?= $service->pricemin; ?></span> euro</p>
			</div>
    		
		</div>
    	<?php endforeach; ?>
	</div>
</div>
<?php endif; ?>

<!-- NAJWNOSZE KLINIKI @todo ostylować -->
<?php if (count($this->newClinics) > 0): ?>
<div class="hero-unit">
	<h1><?= $this->translate('Last added clinics'); ?>:</h1>
	<div class="row-fluid grid-list">
		<?php foreach ($this->newClinics as $clinic): ?>
		<div class="span4 grid-list-item">
    		<a href="<?= $this->url(
			    array('slug' => $clinic->getSlug()), 'clinic', true
			); ?>">
    		<?= $this->ShowClinicLogo($clinic, 'small'); ?></a>
			<div class="grid-desc">
				<a href="<?= $this->url(
				    array('slug' => $clinic->getSlug()), 'clinic', true
				); ?>"><h2><?= $clinic->name; ?></h2></a>
				<p class="city"><span><?= $clinic->city; ?></span></p>
			</div>
		</div>
    	<?php endforeach; ?>
	</div>
</div>
<?php endif; ?>