<div class="hero-unit">
    <h1>Zapraszamy do rejestracji</h1>

    <p>Zapraszamy placówki do rejestracji już teraz.
        Dzięki temu, po premierze serwisu uzyskasz atrakcyjne rabaty i aż 3 miesiące
        abonamentu gratis.</p>

    <p><a class="btn btn-primary btn-large" href="<?= $this->url(array(
        'action' => 'index',
        'controller' => 'register',
        'module' => 'clinic',
    ), 'default', true); ?>">Przejdź do rejestracji &raquo;</a>

        <a class="btn btn-primary" href="<?= $this->url(array(
            'action' => 'index',
            'controller' => 'index',
            'module' => 'clinic',
        ), 'default', true); ?>">Logowanie &raquo;</a></p>
</div>
<div class="hero-unit">
    <h1>Dowiedz się więcej</h1>

    <p>Więcej na temat tego czym jest <strong>Trendmed</strong> możesz dowiedzieć się z naszej prezentacji. </p>

    <p><a class="btn btn-primary btn-large" href="http://www.trendmed.eu/prezentacja/trendmed.pdf">Pobierz
        PDF &raquo;</a></p>
</div>

<!-- @todo ostylować -->
<?php if (count($this->articles) > 0): ?>
<div class="hero-unit articles">
	<h1 class="pull-left"><?= $this->translate('Latest articles:'); ?></h1>
	<a class="btn btn-primary btn-large pull-right" href="#"><?= $this->translate('Show all articles'); ?></a>
	<div class="clearfix"></div>
	<?php foreach ($this->articles as $article): ?>
    	<h2><?= $article->getTitle(); ?></h2>
	    <?php if ($article->getLeadPhoto()): ?>
	            <?= $this->ShowPhoto($article->getLeadPhoto(), 'small', 'ArticlePhoto'); ?>
	        <?php endif; ?>
	        <?= $this->Truncate($article->content)->toLength(100); ?>

	    <a href="<?= $this->url(
	        array('slug' => $article->getSlug()), 'page', true
	    ); ?>"><?= $this->translate('Read more'); ?></a>
    <?php endforeach; ?>
</div>
<?php endif; ?>


<!-- @todo ostylować usługi -->
<?php if (count($this->newServices) > 0): ?>
<div class="hero-unit">
	<h1><?= $this->translate('Last added services'); ?></h1>
	<div class="row-fluid grid-list">
		<?php foreach ($this->newServices as $service): ?>
		<div class="span4 grid-list-item">
			<a href="<?= $this->url(
    		    array('id' => $service->id), 'service', true
    		); ?>"><?= $this->ShowPhoto($service->photos[0], 'small'); ?></a>
    		
    		<div class="grid-desc">
	   			<a href="<?= $this->url(
	    		    array('id' => $service->id), 'service', true
	    		); ?>"><h2><?= $service->category->name; ?></h2></a>
				<p class="price"><?= $this->translate('From'); ?> <span><?= $service->pricemin; ?></span> euro</p>
			</div>
    		
    		
		</div>
    	<?php endforeach; ?>
	</div>
</div>
<?php endif; ?>

<!-- NAJWNOSZE KLINIKI @todo ostylować -->
<?php if (count($this->newClinics) > 0): ?>
<div class="hero-unit">
	<h1><?= $this->translate('Last added clinics'); ?></h1>
	<div class="row-fluid grid-list">
		<?php foreach ($this->newClinics as $clinic): ?>
		<div class="span4 grid-list-item">
    		<a href="<?= $this->url(
			    array('slug' => $clinic->getSlug()), 'clinic', true
			); ?>">
    		<?= $this->ShowClinicLogo($clinic, 'small'); ?></a>
			<div class="grid-desc">
				<a href="<?= $this->url(
				    array('slug' => $clinic->getSlug()), 'clinic', true
				); ?>"><h2><?= $clinic->name; ?></h2></a>
				<p class="city"><span><?= $clinic->city; ?></span></p>
			</div>
		</div>
    	<?php endforeach; ?>
	</div>
</div>
<?php endif; ?>