<a href="<?= $this->url(array('action' => 'index', 'controller' => 'patients', 'module' => 'admin'), 'default', true); ?>">Wróć na liste pacjentów</a>
<p>
    Informacje o rezerwacjach pacjenta: <?= $this->patient->username; ?>.<br>
    Ostatnie logowanie pacjenta do portalu: <?= $this->patient->lastLoginTime->format("d-m-Y H:i:s"); ?>
</p>
<?php if(count($this->patient->reservations) > 0): ?>
    <table class="table">
        <thead>
            <tr>
                <th>
                    Numer
                </th>
                <th>
                    Data złożenia
                </th>
                <th>
                    Status
                </th>
                <th>
                    Klinika
                </th>
                <th>
                    Status platności
                </th>
                <th>
                    Usługi
                </th>
            </tr>
        </thead>
    <?php foreach($this->patient->reservations as $reservation): ?>
        <tr>
            <td>
                <?php $status =  $reservation->getStatusAsArray(); ?>

                <?= $reservation->id;?>
            </td>
            <td>
                <?= $reservation->created->format("d-m-Y H:i:s");?>
            </td>
            <td>
                <?= $this->translate($reservation->status); ?>
                <?php if(! count($status['actions']['patient']) >0  && $reservation->status != 'closed'): ?><br>
                <em><?= $this->translate('oczekuje na reakcje kliniki'); ?></em>
                <?php endif; ?>
            </td>
            <td>
                <a href="<?= $this->url(array(
                    'slug' => $reservation->clinic->slug,
                ), 'clinic', true); ?>"><?= $reservation->clinic->name; ?></a>
            </td>
            <td>
<?php switch($reservation->getBillStatus()): ?>
<?php case \Trendmed\Entity\Reservation::BILL_STATUS_NOT_PAID: ?>
    <strong><?= $this->translate('Bill not paid yet'); ?></strong><br>
    <a href="<?= $this->url(array(
        'action' => 'change-pay-bill-state',
        'new-state' => 'paid',
        'controller' => 'reservations',
        'module' => 'admin',
        'id' => $reservation->id,
    ), 'default', true);?>" class="confirm">Oznacz jako opłacona</a><br>
<?php break;?>
<?php case \Trendmed\Entity\Reservation::BILL_STATUS_NOT_WANTED: ?>
Nie wymagana przy tej rezerwacji.
<?php break;?>
<?php case \Trendmed\Entity\Reservation::BILL_STATUS_PAID: ?>
    Kaucja wpłacona<br>
    <a href="<?= $this->url(array(
        'action' => 'change-pay-bill-state',
        'controller' => 'reservations',
        'module' => 'admin',
        'new-state' => 'not-paid',
        'id' => $reservation->id,
    ), 'default', true);?>" class="confirm">Oznacz jako nieopłacona</a><br>
<?php break; ?>
<?php endswitch; ?>
            </td>
            <td>
            <ul>
                <?php foreach($reservation->services as $service): ?>
                <li>
                    <?= $service->category->name; ?>
                </li>
                <?php endforeach; ?>
            </ul>
            </td>
        </tr>
        <tr>
            <td colspan="6">
                Komentarz od pacjenta do kliniki:<br>
                <blockquote><?= $reservation->question;?></blockquote><br>
                Odpowiedź kliniki:<br>
                <blockquote><?= $reservation->answer;?></blockquote>
            </td>
        </tr>
        <?php endforeach; ?>
    </table>
<?php else: ?>
    Pacjent nie ma żadnych rezerwacji w systemie.
<?php endif; ?>
