<p>
    Witamj,<br>
    <br>
    prosiłeś o zmianę adresu emaul do Twojego konta na serwisie <a herf="http://<?= $_SERVER['HTTP_HOST'];?>">Trendmed.eu</a>
    <br>
    Aby potwierdzić zmianę proszę przejść na podany link lub skopiować go w całości do przeglądarki:
    <a href="<?= $this->link; ?>"><?= $this->link; ?></a>
    <br>
    Pozdrawiamy<br>
    Zespół Trendmed<br>
    <br>
    <br>
    Jeśli masz jakiekolwiek pytania dotyczące funkcjonowania portalu <a href="http://<?= $_SERVER['HTTP_HOST'];?><?= $this->url(array('type' => "feedback"), 'contact'); ?>">skontaktuj się z nami</a>. <br>
</p>