<!DOCTYPE html>
<html lang="pl">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" >
</head>
<body>
<p>
    Dzień Dobry,<br>
    prosiłeś aby zmienić adres e-mail do Twojego konta na serwisie Trendmed.eu
</p>
<p>
    Aby potwierdzić zmianę proszę udać się pod adres:
    <a href="<?= $this->link; ?>"><?= $this->link; ?></a>
</p>
<footer>
    Zespół Trendmed
</footer>
</body>
</html>
