<?php if (count($this->reservations) >0 ): ?>
<table class="table">
    <thead>
    <tr>
        <th>
            <?= $this->translate('Date'); ?>
        </th>
        <th>
            <?= $this->translate('Clinic'); ?>
        </th>
        <th>
            <?= $this->translate('Services'); ?>
        </th>
        <th>
            <?= $this->translate('Status'); ?>
        </th>
        <th>
            <?= $this->translate('Actions'); ?>
        </th>
    </tr>
    </thead>
    <tbody>
        <?php foreach ($this->reservations as $reservation): ?>
            <tr>
                <td><?= $reservation->created->format("d-m-Y"); ?></td>
                <td><?= $reservation->clinic->name; ?></td>
                <td>
                    <ul>
                    <?php foreach($reservation->services as $service): ?>
                        <li><?= $service->category->name; ?></li>
                    <?php endforeach; ?>
                    </ul>
                </td>
                <td>
                    <?php $status =  $reservation->getStatusAsArray(); echo $this->translate($status['name']); ?>
                </td>
                <td>

                    <div class="btn-group">
                        <a class="btn" href="#myModal" data-toggle="modal"><?= $this->translate('See details'); ?></a>
                        <button class="btn dropdown-toggle" data-toggle="dropdown">
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu">
                            <!-- dropdown menu links -->
                            <?php foreach($status['actions']['patient'] as $action): ?>
                            <li>
                                <a href="<?= $this->url(array('id' => $reservation->id),
                                    $this->config->reservation->action->patient->$action->routeName); ?>">
                                    <?= $this->translate($this->config->reservation->action->patient->$action->name); ?>
                                </a>
                            </li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php endif;?>

<?= $this->ShowFavClinics($this->LoggedUser()); ?>