<br>
<?php printf($this->translate('Regards'))?>, <br>
<?php printf($this->translate('Trendmed.eu Team'))?><br>
<br>
<br>
<?php printf($this->translate('If you require any further information please do not hesitate <a href="http://%s">to contact us.</a>', $_SERVER['HTTP_HOST'].$this->url(array('type' => "feedback"), 'contact')))?><br>
<a href="http://<?= $_SERVER['HTTP_HOST'];?>"><img src="file://img/logo.png" /></a>
