<p>
    <?php printf($this->translate('Hello!'))?>, <br>
    <br>
    Klinika <?= $this->reservation->clinic->name; ?> anulowała Twoją rezerwację numer <?= $this->reservation->id; ?>.<br>
    <br>
    <?php if (!$this->reservation->answer == "") : ?>
        Dodatkowy komentarz kliniki: <?= $this->reservation->answer ?> <br>   
    <?php endif; ?>
    <br>
    Szczegóły rezerwacji znajdziesz na swoim profilu. <br>
    <br>
    Pozdrawiamy<br>
    Zespół Trendmed<br>
    <br>
    <br>
    <?php printf($this->translate('If you require any further information please do not hesitate <a href="http://%s">to contact us.</a>', $_SERVER['HTTP_HOST'].$this->url(array('type' => "feedback"), 'contact')))?><br>
    <a href="http://<?= $_SERVER['HTTP_HOST'];?>"><img src="<?= $_SERVER['HTTP_HOST'];?>/img/logo.png" /></a>
</p>