<p>
    <?php printf($this->translate('Hello!'))?><br>
    <br>
    <?php printf($this->translate('Clinic <a href="http://%s">%s</a> canceled your reservation number %u', $_SERVER['HTTP_HOST'].$this->url(array('slug' => $this->reservation->clinic->getSlug()), 'clinic'),$this->reservation->clinic->name,$this->reservation->id ))?><br>
    <?php if (!$this->reservation->answer == "") : ?>
    <b><?php printf($this->translate('Additional remark from clinic:'))?> <?= $this->reservation->answer ?></b><br>   
    <?php endif; ?>

</p>
<?= $this->render('patient/_patientEmailFooter.phtml'); ?>