<p>
    <?php printf($this->translate('Hello!'))?><br>
    <br>
    <?php printf($this->translate('We can confirm that You have placed reservation in the clinic <a href="http://%s">%s</a>. Your reservation number is %u, remember it.' , $_SERVER['HTTP_HOST'].$this->url(array('slug' => $this->reservation->clinic->getSlug()), 'clinic'), $this->reservation->clinic->name , $this->reservation->id)) ?> <br>
    <br>
    <?php printf($this->translate('You have chosen services:'))?><br>
    <?php foreach ($this->reservation->services as $service): ?>
     - <a href="http://<?= $_SERVER['HTTP_HOST'];?><?= $this->url(array('id' =>$service->id), 'service'); ?>"><?= $service->category->name; ?></a><br>
    <?php endforeach; ?>
     
     <?php printf($this->translate('Your proposed dates of reservation, from %s to %s' , $this->reservation->dateFrom->format('d-m-Y'), $this->reservation->dateTo->format('d-m-Y') ))?> <br>
    
    <?php if (!$this->reservation->question == ""): ?>
     <b> <?php printf($this->translate('Your comment'))?> <?= $this->reservation->question?><br>   </b>
    <?php endif; ?>
</p>
<?= $this->render('patient/_patientEmailFooter.phtml'); ?>