<p>
    <?php printf($this->translate('Hello!'))?>, <br>
    <br>
    <?php printf($this->translate('We can confirm that You have placed reservation in the clinic %s. Your reservation number is %u, remember it.', $this->reservation->clinic->name, $this->reservation->id )) ?> <br>
    <br>
    Wybrane przez Ciebie usługi: <br>
    <?php foreach ($this->reservation->services as $service): ?>
     - <a href="http://<?= $_SERVER['HTTP_HOST'];?><?= $this->url(array('id' =>$service->id), 'service'); ?>"><?= $service->category->name; ?></a><br>
    <?php endforeach; ?>
     
     <?php printf($this->translate('Your proposed dates of reservation, from %s to %s' , $this->reservation->dateFrom->format('d-m-Y'), $this->reservation->dateTo->format('d-m-Y') ))?> <br>
    
    <?php if (!$this->reservation->question == ""): ?>
        <?php printf($this->translate('Your comment'))?> <?= $this->reservation->question?><br>   
    <?php endif; ?>
    <br>
    <?php  printf($this->translate('Reservation needs to be confirmed by the clinic. You will be informed about that via email.')) ?>
    Możesz też <a href="http://<?= $_SERVER['HTTP_HOST']; ?><?= $this->url(array('module'=>'patient', 'controller'=>'reservations', 'action'=>'view', 'id'=>$this->reservation->id), 'default')?>">śledzić status na swoim profilu</a>.
    <br>
    Pozdrawiamy<br>
    Zespół Trendmed<br>
    <br>
    <br>
    <?php printf($this->translate('If you require any further information please do not hesitate <a href="http://%s">to contact us.</a>', $_SERVER['HTTP_HOST'].$this->url(array('type' => "feedback"), 'contact')))?><br>
    <a href="http://<?= $_SERVER['HTTP_HOST'];?>"><img src="<?= $_SERVER['HTTP_HOST'];?>/img/logo.png" /></a>
</p>
