<p>
    Witaj,<br>
    <br>
    Klinika <?= $this->reservation->clinic->name; ?> odpowiedziała na Twoją rezerwację numer <?= $this->reservation->id; ?> i proponuje alternatywny termin wizyty:<br>
    Od <?= $this->reservation->alternativeDateFrom->format("d-m-Y"); ?> do
    <?= $this->reservation->alternativeDateTo->format("d-m-Y"); ?><br>
    <br>
    <?php if (!$this->reservation->answer == ""): ?>
        Kometarz kliniki do Twojej rezerwacji: <?= $this->reservation->answer ?> <br>   
    <?php endif; ?>
    <br>
    Możesz teraz<br>
     - <a href="http://<?= $_SERVER['HTTP_HOST'];?><?= $this->url(array('id' => $this->reservation->id), 'action_patient_confirm'); ?>">potwierdzić nowe daty</a><br>
     - <a href="http://<?= $_SERVER['HTTP_HOST'];?><?= $this->url(array('id' => $this->reservation->id), 'action_cancel'); ?>">lub zrezygnować z rezerwacji</a><br> 
     <br>
    Szczegóły rezerwacji znajdziesz na swoim profilu. <!--Link: http://trendmed.localhost/patient/reservations/view/id/62 --> .
    Pozdrawiamy<br>
    Zespół Trendmed<br>
    <br>
    <br>
    Jeśli masz jakiekolwiek pytania dotyczące funkcjonowania portalu <a href="http://<?= $_SERVER['HTTP_HOST'];?><?= $this->url(array('type' => "feedback"), 'contact'); ?>">skontaktuj się z nami</a>. <br>
    <a href="http://<?= $_SERVER['HTTP_HOST'];?>"><img src="<?= $_SERVER['HTTP_HOST'];?>/img/logo.png" /></a>
</p>
