<p>
    <?php printf($this->translate('Hello!'))?>, <br>
    <br>
        <?php printf($this->translate('Your reservation no %u in clinic <a href="http://%s">%s</a> has been paid.' , $this->reservation->id , $_SERVER['HTTP_HOST'].$this->url(array('slug' => $this->reservation->clinic->getSlug()), 'clinic'),$this->reservation->clinic->name))?><br>
    <br>
    <?php printf($this->translate('Your order includes:'))?><br>
    <?php foreach ($this->reservation->services as $service): ?>
     - <a href="http://<?= $_SERVER['HTTP_HOST'];?><?= $this->url(array('id' => $service->id, ), 'service') ?>"><?= $service->category->name; ?></a><br>
    <?php endforeach; ?>
</p>
<?= $this->render('patient/_patientEmailFooter.phtml'); ?>