<p>
    <?php printf($this->translate('Hello!'))?>, <br>
    <br>
    <?= $this->translate('Aby ustanowić nowe hasło dla Twojego profilu na portalu Trendmed.eu proszę przejść na niżej podany link lub skopiować
    go w całości do przeglądarki:'); ?>
    <br>
    <strong><a href="<?= $this->link;?>" target="_blank"><?= $this->link;?></a></strong><br>
    <br>
    <?= $this->translate('Jeżeli nie używaleś funkcji przypomienia hasła do profilu, zignoruj tą wiadomość.'); ?><br>
</p>
<?= $this->render('patient/_patientEmailFooter.phtml'); ?>