<p>
    Witaj,<br>
    <br>
    <?= $this->translate('Aby ustanowić nowe hasło dla Twojego profilu na portalu Trendmed.eu proszę przejść na niżej podany link lub skopiować
    go w całości do przeglądarki:'); ?>
    <br>
    <strong><a href="<?= $this->link;?>" target="_blank"><?= $this->link;?></a></strong><br>
    <br>
    <?= $this->translate('Jeżeli nie używaleś funkcji przypomienia hasła do profilu, zignoruj tą wiadomość.'); ?><br>
    <br>
    Pozdrawiamy<br>
    Zespół Trendmed<br>
    <br>
    <br>
    Jeśli masz jakiekolwiek pytania dotyczące funkcjonowania portalu <a href="http://<?= $_SERVER['HTTP_HOST'];?><?= $this->url(array('type' => "feedback"), 'contact'); ?>">skontaktuj się z nami</a>. <br>
</p>