<p>
    <?= $this->translate('Aby ustanowić nowe hasło dla Państwa profilu na portalu Trendmed.eu proszę przejść na niżej podany link lub skopiować
    go całego do przeglądarki.'); ?>
</p>
<p>
    <strong><a href="<?= $this->link;?>" target="_blank"><?= $this->link;?></a></strong>
</p>
<p>
    <?= $this->translate('Jeżeli nie używaliście Państwo funkcji przypomienia hasła do profilu, prosimy o zignorowanie tej wiadomości.'); ?>
</p>