<p>
    <?php printf($this->translate('Hello!'))?>, <br>
    <br>
    Przypominamy o konieczności opłacenia zaliczki za Twoje usługi aby ostatecznie zakończyć proces rezerwacji w klinice <?= $this->reservation->clinic->name; ?>. <br>
    <br>
    Szczegóły rezerwacji: <br>
     - Numer <?= $this->reservation->id; ?>.<br>
     - W skład zamawianych usług wchodzą:
    <?php foreach ($this->reservation->services as $service): ?> <a href="<?= $this->url(array('id' => $this->reservation->id, ), 'service') ?>"><?= $service->category->name; ?></a>, 
    <?php endforeach; ?>.
    - Twój termin wizyty: od <?= $this->reservation->dateFrom->format('d-m-Y'); ?> do <?= $this->reservation->dateTo->format('d-m-Y'); ?>. <br>
    <br>
    Szczegóły rezerwacji znajdziesz też na swoim profilu.<br>
    <br>
    Pozdrawiamy<br>
    Zespół Trendmed<br>
    <br>
    <br>
    <?php printf($this->translate('If you require any further information please do not hesitate <a href="http://%s">to contact us.</a>', $_SERVER['HTTP_HOST'].$this->url(array('type' => "feedback"), 'contact')))?><br>
    <a href="http://<?= $_SERVER['HTTP_HOST'];?>"><img src="<?= $_SERVER['HTTP_HOST'];?>/img/logo.png" /></a>
</p>
