<div class="alert alert-info">
    <a class="close" data-dismiss="alert" href="#">&times;</a>

    Pamiętaj, każda placówka moze wystąpić w danej kategorii tylko raz,
    dlatego opisz dokładnie swoją ofertę w danym zakresie.
    Dodane zdjęcia będą wspólne dla wszystkich wersji językowych usługi.
</div>
<div id="editClinic" class="form-horizontal textareas"><?= $this->form; ?></div>


<? if(count($this->service->photos) > 0): ?>
    <h3>Zdjęcia usługi</h3>
        <p>
            Możesz wgrać maksymalnie <?= $this->config->services->photo->limit; ?> zdjęć do każdej usługi. Zostało Ci
            <?= $this->form->getPhotosLeft(); ?>. Możesz usunąć zdjęcia aby zrobić miejsce na nowe.
        </p>
    <ul class="thumbnails">
    <? foreach($this->service->photos as $photo): ?>
    <li class="thumbnail">
        <?= $this->ShowPhoto($photo, 'medium', 'services'); ?>
        <p class="caption"><a href="<?= $this->url(
            array(
                'action' => 'delete-service-photo',
                'controller' => 'services',
                'module' => 'clinic',
                'id'    => $photo->id,
            )
        ); ?>" class="btn btn-danger confirm"> <i class="icon-white icon-trash"> </i></a> </p>
    </li>
    <? endforeach; ?>
    </ul>
<? endif; ?>
