<? if (count($this->services) < 1 ): ?>
<div class="alert alert-info">
    <strong>Nie dodałeś żadnych usług</strong><br />
    Usługi pozwolą Twoim potencjalnym pocjentom odnaleźć Cię w naszym katalogu. To prostę, zacznij od dodania nowej usługi.
</div>
<? endif; ?>
<a class="btn" href="<?= $this->url(array('action' => 'manage-services')); ?>"><?= $this->translate('Add new service'); ?></a>
<? if (count($this->services) > 0 ): ?>
    <table class="table">
        <thead>
            <tr>
                <th>Kategoria</th>
                <th>Opis</th>
                <th>Cena od - do</th>
                <th>Opcje</th>
            </tr>
        </thead>
        <tbody>
    <? foreach($this->services as $service): ?>
        <tr>
            <td><?= $service->category->name; ?></td>
            <td><?= $service->description; ?></td>
            <td><?= $service->pricemin; ?> - <?= $service->pricemax; ?></td>
            <td>
                <a href="<?= $this->url(array('action' => 'manage-services',    'id' => $service->getId())); ?>"><?= $this->translate('Edit'); ?></a>
                <a href="<?= $this->url(array('action' => 'delete-service',     'id' => $service->getId())); ?>"><?= $this->translate('Delete'); ?></a>
            </td>
        </tr>
    <? endforeach; ?>
        </tbody>
    </table>
<? else: ?>

<? endif; ?>