<p>Tutaj możesz zmienić zdjęcia które wyświetlą się przy Twojej ofercie w kategorii "<?=$this->service->category->name; ?>".</p>
<? if (count ($this->service->getPhotos()) > 0): ?>
<ul class="thumbnails">
    <? foreach($this->service->getPhotos() as $photo): ?>
    <li class="thumbnail">
        <?= $this->ShowPhoto($photo, 'medium', 'services'); ?>
        <p class="caption"><a href="<?= $this->url(
            array(
                'action' => 'delete-service-photo',
                'controller' => 'services',
                'module' => 'clinic',
                'id'    => $photo->id,
            )
        ); ?>" class="btn btn-danger confirm"> <i class="icon-white icon-trash"> </i></a> </p>
    </li>
    <? endforeach; ?>
</ul>
<? endif; ?>
<?= $this->form; ?>