<? if(count($this->pages)): ?>
<? //TODO ?>
<table class="table table-striped table-bordered table-condensed">
    <thead>
    <tr>
        <th>#Id</th>
        <th><?= $this->translate('Title'); ?></th>
        <th><?= $this->translate('Lead photo'); ?></th>
        <th><?= $this->translate('Type'); ?></th>
        <th><?= $this->translate('Link'); ?></th>
        <th><?= $this->translate('Last Edited'); ?></th>
        <th><?= $this->translate('Created'); ?></th>
        <th> </th>
    </tr>
    </thead>
    <tbody>
        <? foreach($this->pages as $page): ?>
    <tr>
        <td><?= $page->id; ?></td>
        <td><?= $page->title; ?> <? if(!$page->isActive()): ?><small><em>(<?= $this->translate('not active');?>)</em></small><? endif;?></td>
        <td><?php if($page->getLeadPhoto()): ?><?= $this->ShowPhoto($page->leadPhoto, 'small', 'ArticlePhoto'); ?><?php endif; ?></td>
        <td><?= $page->getTypeName(); ?></td>
        <td>
            <input disabled="disabled" type="text" value="http://<?= $_SERVER['HTTP_HOST'].$this->url( array('slug' => $page->slug), 'page', true); ?>"/>
        </td>
        <td><?= $page->modified->format("m/d/Y H:i:s"); ?></td>
        <td><?= $page->created->format("m/d/Y H:i:s"); ?></td>
        <td>
            <div class="btn-group">
                <a class="btn" href="<?= $this->url(array(
                    'action' => 'save-page',
                    'id' => $page->id,
                    'module' => 'admin',
                    'controller' => 'pages'
                ),null, true); ?>"><?= $this->translate('Edit page'); ?></a>
                <button class="btn dropdown-toggle" data-toggle="dropdown"><span class="caret"></span></button>
                <ul class="dropdown-menu">
                    <li><a class="" href="<?= $this->url(array(
                        'slug' => $page->slug,
                    ),'page', true); ?>"><?= $this->translate('See'); ?></a></li>
                    <li class="divider"></li>
                    <li><a class="confirm" href="<?= $this->url(array(
                        'action' => 'delete-page',
                        'id' => $page->id,
                        'module' => 'admin',
                        'controller' => 'pages'
                    ),'default', true); ?>"><?= $this->translate('Delete page'); ?></a></li>
                    <li><a class="confirm" href="<?= $this->url(array(
                        'action' => 'activate',
                        'id' => $page->id,
                        'module' => 'admin',
                        'controller' => 'pages'
                    )); ?>"><?= $this->translate('Toggle active'); ?></a></li>
                </ul>
            </div>

        </td>
    </tr>
        <? endforeach; ?>
    </tbody>
</table>
<? else: ?>
<div class="alert">
    <button class="close" data-dismiss="alert">×</button>
    <?= $this->translate('<strong>Warning!</strong> No pages in the system');?>
</div>
<? endif; ?>
