<?php if (count($this->paginator)): ?>
<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Nazwa</th>
            <th>Adres</th>
            <th>Reprezentant</th>
            <th>Dodano</th>
            <th>Ostatnio zalogowny</th>
        </tr>
    </thead>
<?php foreach ($this->paginator as $item): ?>
    <tr>
        <td><?= $item->id; ?></td>
        <td><?= $item->name; ?><br /><strong>Typ:</strong> <?= $this->translate($item->type); ?></td>
        <td><address>
        <?= $item->streetaddress; ?><br />
        <?= $item->postcode; ?> <?= $item->city; ?></address></td>
        <td><?= $item->repName; ?><br />
        <?= $item->repPhone; ?><br />
        <?= $item->repEmail; ?></td>
        <td><?= $item->created->format('d/m/Y'); ?></td>
        <td>
        <? if($item->lastLoginTime): ?>
        <?= $item->lastLoginTime->format('d/m/Y'); ?>
        <? else: ?>
            Placówka się nie logowała.
        <? endif; ?>
        </td>
    </tr>
<?php endforeach; ?>
</table>
<?php endif; ?>
