<h2>Rezerwacja numer #<?= $this->reservation->id; ?></h2>
<dl>
	<div class="row-fluid">
		<div class="span6">
			<dt>Złożona przez</dt>
		    <dd><?= $this->reservation->patient->name;?> <br>Telefon: <?= $this->reservation->patient->phoneNumber; ?><br>
		        E-mail: <a href="mailto:<?= $this->reservation->patient->getEmailaddress(); ?>">
		            <?= $this->reservation->patient->getEmailaddress(); ?></a></dd>
		</div>
		<div class="span6">
			<dt>Data złożenia rezerwacji</dt>
		    <dd><?= $this->reservation->created->format("d-m-Y h:i:s");?></dd>
		</div>
	</div>
	<div class="row-fluid">
			<div class="span6">
				<dt>
			        Status opłacenia rezerwacji
			    </dt>
			    <dd>
	                <?php switch($this->reservation->getBillStatus()):
						case \Trendmed\Entity\Reservation::BILL_STATUS_NOT_PAID: ?>
	    <strong><?php echo $this->translate('Bill not paid yet'); ?></strong>
	    <?php break;?>
	<?php case \Trendmed\Entity\Reservation::BILL_STATUS_NOT_WANTED: ?>
	    Nie wymagana przy tej rezerwacji.
	<?php break;?>
	<?php case \Trendmed\Entity\Reservation::BILL_STATUS_PAID: ?>
	    Kaucja wpłacona
	<?php break; ?>
	                <?php endswitch; ?>
	            </dd>
			</div>
		<div class="span6">
			<dt>Zamówione usługi</dt>
		    <dd>
		        <ul>
		            <?php foreach($this->reservation->services as $service): ?>
		            <li><?= $service->category->name;?></li>
		            <?php endforeach; ?>
		        </ul>
		    </dd>
            <?php if($this->reservation->isGroupReservation()): ?>
            <dt>
                <?= $this->translate('Group reservation status'); ?>
            </dt>
            <dd>
                <?= sprintf($this->translate(
                    '%u confirmed reservations out of %u invites', $this->reservation->getGroupReservation()->getConfirmedCount(), $this->reservation->getGroupReservation()->getTotalReservationsCount())
            ); ?><br>
                <?= sprintf($this->translate('Current discount is %u', $this->reservation->getGroupReservation()->getCurrentBonusRate())); ?>%
                <br>
                Rezerwacje powiązane grupowo to:
                <ul>
                    <?php foreach($this->reservation->getGroupReservation()->getReservations() as $reservation): ?>
                        <li>#<?= $reservation->id; ?></li>
                    <?php endforeach; ?>
                </ul>

            </dd>
            <?php endif; ?>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span6">
			<dt>Data proponowana przez klienta na wizytę</dt>
		    <dd>
		        Od <?= $this->reservation->dateFrom->format("d-m-Y"); ?> do <?= $this->reservation->dateTo->format("d-m-Y"); ?>
		    </dd>
		</div>
		<div class="span6">
			<?php if($this->reservation->newDateWasProposed() == true): ?>
		        <dt>Alternatywna data proponowana przez klinikę na wizytę</dt>
		        <dd>
		            Od <?= $this->reservation->alternativeDateFrom->format("d-m-Y"); ?> do <?= $this->reservation->alternativeDateTo->format("d-m-Y"); ?>
		        </dd>
		    <?php endif; ?>
		</div>
	</div>
    <div class="row-fluid">
		<div class="span6">
			<dt>Dodatkowy komentarz i pytania od klienta</dt>
		    <dd>
		        <?php if(null !== $this->reservation->question): ?>
		        <?= $this->reservation->question; ?>
		        <?php else :?>
		        Klient nie zawarł żadnych dodatkowych uwag ani pytań.
		        <?php endif; ?>
		    </dd>
		</div>
	
	</div>
	<div class="row-fluid">
		<div class="span6">
			<?php if($this->reservation->rating): ?>
		        <dt>
		            Ocena wizyty przez pacjenta
		        </dt>
		        <dd>
		            <ul>
		                <li>Ocena ceny usługi: <?= $this->reservation->rating->priceRate; ?></li>
		                <li>Ocena wykonania usługi: <?= $this->reservation->rating->serviceRate; ?></li>
		                <li>Ocena obsługi: <?= $this->reservation->rating->stuffRate; ?></li>
		            </ul>
		            Dodatkowy komentarz: <?= $this->reservation->rating->comment ?: 'brak komentarza'; ?>
		        </dd>
		    <?php endif; ?>

		</div>
		<div class="span6">
		
		</div>
	</div>
</dl>