<h2>Rezerwacja numer #<?= $this->reservation->id; ?></h2>
<dl>
	<div class="row-fluid">
		<div class="span6">
			<dt>Złożona przez</dt>
		    <dd><?= $this->reservation->patient->name;?></dd>
		</div>
		<div class="span6">
			<dt>Data złożenia rezerwacji</dt>
		    <dd><?= $this->reservation->created->format("d-m-Y h:i:s");?></dd>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span6">
			<dt>Kontakt do pacjenta</dt>
		    <dd>Telefon: <?= $this->reservation->patient->phoneNumber; ?><br>
		        E-mail: <a href="mailto:<?= $this->reservation->patient->getEmailaddress(); ?>">
		            <?= $this->reservation->patient->getEmailaddress(); ?></a></dd>
		</div>
		<div class="span6">
			<dt>Zamówione usługi</dt>
		    <dd>
		        <ul>
		            <?php foreach($this->reservation->services as $service): ?>
		            <li><?= $service->category->name;?></li>
		            <?php endforeach; ?>
		        </ul>
		    </dd>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span6">
			<dt>Data proponowana przez pacjenta na wizytę</dt>
		    <dd>
		        Od <?= $this->reservation->dateFrom->format("d-m-Y"); ?> do <?= $this->reservation->dateTo->format("d-m-Y"); ?>
		    </dd>
		</div>
		<div class="span6">
			<?php if($this->reservation->newDateWasProposed() == true): ?>
		        <dt>Alternatywna data proponowana przez klinikę na wizytę</dt>
		        <dd>
		            Od <?= $this->reservation->alternativeDateFrom->format("d-m-Y"); ?> do <?= $this->reservation->alternativeDateTo->format("d-m-Y"); ?>
		        </dd>
		    <?php endif; ?>
		</div>
	</div>
    <div class="row-fluid">
		<div class="span6">
			<dt>Dodatkowy komentarz i pytania od pacjenta</dt>
		    <dd>
		        <?php if(null !== $this->reservation->question): ?>
		        <?= $this->reservation->question; ?>
		        <?php else :?>
		        Pacjent nie zawarł żadnych dodatkowych uwag ani pytań.
		        <?php endif; ?>
		    </dd>
		</div>
		<div class="span6">
			<dt>
		        Status opłacenia rezerwacji
		    </dt>
		    <dd>
		        <?php if ($this->reservation->getBillStatus() == \Trendmed\Entity\Reservation::BILL_STATUS_NOT_PAID): ?>
		            <strong><?= $this->translate('Bill not paid yet'); ?></strong>
		        <?php else: ?>
		            Kaucja wpłacona lub nie wymagana przy tej rezerwacji.
		        <?php endif; ?>
		    </dd>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span6">
			<?php if($this->reservation->rating): ?>
		        <dt>
		            Ocena wizyty przez pacjenta
		        </dt>
		        <dd>
		            <ul>
		                <li>Ocena ceny usługi: <?= $this->reservation->rating->priceRate; ?></li>
		                <li>Ocena wykonania usługi: <?= $this->reservation->rating->serviceRate; ?></li>
		                <li>Ocena obsługi: <?= $this->reservation->rating->stuffRate; ?></li>
		            </ul>
		            Dodatkowy komentarz: <?= $this->reservation->rating->comment ?: 'brak komentarza'; ?>
		        </dd>
		    <?php endif; ?>
		</div>
		<div class="span6">
		
		</div>
	</div>
    

    

    
    

    

   

    

</dl>