<a class="btn" href="<?= $this->url(array('action' => 'index', 'controller' => 'profile', 'module' => 'clinic'), 'default', true); ?>">&laquo; lista rezerwacji</a>

<?= $this->partial('reservations/_reservationDetails.phtml', array('reservation' => $this->reservation)); ?>
    <h3 class="reservationNotice">Uwaga, potwierdzając rezerwację zwierają Państwo umowę z rezerwującym.</h3>
<?= $this->form; ?>