<a class="btn" href="<?= $this->url(
    array('action' => 'index', 'controller' => 'profile', 'module' => 'clinic'), 'default', true
); ?>">&laquo; lista rezerwacji</a>

<?= $this->partial('reservations/_reservationDetails.phtml', array('reservation' => $this->reservation)); ?>
    <h3 class="reservationNotice">
        Anulowanie rezerwacji oznacza zamknięcie tej rezerwacji. Pacjent zostanie poinformowany przez e-mail o twojej decyzji.
        Dobrą praktyką jest dopisanie komentarze z powodem anulowania rezerwacji.
    </h3>
<?= $this->form; ?>