<a class="btn" href="<?= $this->url(array('action' => 'index', 'controller' => 'profile', 'module' => 'clinic'), 'default', true); ?>">&laquo; lista rezerwacji</a>

<?= $this->partial('reservations/_reservationDetails.phtml', array('reservation' => $this->reservation)); ?>
<h3 class="reservationNotice">
    Jeżeli data sugerowana przez klienta nie może być zrealizowana, można zaproponować alternatywną datę,
    którą klient będzie mógł przyjąć lub odrzucić. Można także przekazać dodatkową informacje.
</h3>
<?= $this->form; ?>
<script type="text/javascript">
    $(".datepicker").datepicker();
</script>