<a class="btn" href="<?= $this->url(array('action' => 'index', 'controller' => 'profile', 'module' => 'clinic'), 'default', true); ?>">&laquo; lista rezerwacji</a>

<?= $this->partial('reservations/_reservationDetails.phtml', array('reservation' => $this->reservation)); ?>
<p>
    Jeżeli data wyznaczona przez pacjenta nie pasuję wam, możecie wyznaczyć alternatywną datę którą pacjent będzie mógł
    przyjąć lub odrzucić. Dodatkowo, możecie zawrzeć komentarz.
</p>
<?= $this->form; ?>
<script type="text/javascript">
    $(".datepicker").datepicker();
</script>