<fieldset>
    <?= $this->element->username ?>
    <?= $this->element->password ?>
	<?= $this->element->rememberMe ?>
</fieldset>
<div class="form-actions">
	<?= $this->element->signin ?>

    <a href="<?= $this->url(array('action' => 'index', 'controller' => 'register', 'module' => 'patient'), 'default', true); ?>" class="btn"><?= $this->translate('Create account for free!'); ?></a>
	<a class="btn facebook-login"><?= $this->translate('Login via Facebook'); ?></a>
    <a href="<?= $this->url(array('action' => 'password-recovery'), 'default', true); ?>"><?= $this->translate('Password recovery'); ?></a>
</div>

