<div id="clinicProfile">

    <div class="row">

        <div class="left">
            <h1><?= $this->clinic->name; ?></h1>
            <address>
                <?= $this->clinic->streetaddress; ?>, <?= $this->clinic->postcode; ?> <?= $this->clinic->city; ?>,
                <?= $this->clinic->province; ?>
            </address>
        </div>

        <div class="right rating">
            <span class="count"><?= $this->clinic->rating; ?>%</span>
            <big>Rating</big><br/ >
            <small>based on <?= $this->clinic->getReviews()->count(); ?> reviews</small>
        </div>

        <div class="globalClear"></div>

        <?= $this->ShowClinicLogo($this->clinic, 'small'); ?>
        
        <?= $this->clinic->description; ?>
		
		<div class="globalClear"></div>
		
        <a class="btn btn-primary" id="buttonBook" href="<?= $this->url(array('slug' => $this->clinic->slug), 'newReservation'); ?>"><?= $this->translate('book visit'); ?></a>
        
        <a id="seeProfile" href="<?= $this->url(array(
            'slug' => $this->clinic->slug,
        ), 'clinic', true); ?>" class="btn btn-primary"><?= $this->translate('See profile'); ?></a>
		
		<div class="globalClear"></div>
        
    </div>

</div>