<div id="clinicProfile">

<div class="row">
	
	<div class="left">
		<h1><?= $this->clinic->name; ?></h1>
	    <address>
	        <?= $this->clinic->streetaddress; ?>, <?= $this->clinic->postcode; ?> <?= $this->clinic->city; ?>,
	        <?= $this->clinic->province; ?>
			<span class="map"><a href="<?= $this->url(array('slug' => $this->clinic->getSlug()), 'clinic'); ?>#map"><?= $this->translate('Show on map'); ?></a></span>
	    </address>
    </div>
        
    <div class="right rating">
        <span class="count"><?= $this->clinic->rating; ?>%</span>
        <?= $this->AddToFavorite($this->clinic); ?>
        <big><?= $this->translate('Rating'); ?></big><br/ >
		<small><?= $this->translate('based on '); ?><?= $this->clinic->reviews->count(); ?><?= $this->translate(' reviews'); ?></small>
    </div>
    

    <div class="globalClear"></div>
    
    <div class="row-fluid">
        <div class="span3 clinicLogo">
			<?= $this->ShowClinicLogo($this->clinic); ?>
		</div>
        <div class="span9">
			<div class="row-fluid">
				<div class="span12">
					<? foreach($this->clinic->photos as $photo): ?>
			        <?= $this->ShowPhoto($photo, 'small'); ?>
			        <? endforeach; ?>
				</div>
			</div>
			<div class="row-fluid">
				<div class="span12">
					<?php if($this->LoggedUser()->roleName == 'patient'): ?>
					    <a id="buttonBook" href="<?= $this->url(array('slug' => $this->clinic->slug), 'newReservation', true);?>" class="btn-primary buttonBook"><?= $this->translate('Book now'); ?></a>
					<?php else: ?>
					    <?= $this->LoggedLink($this->translate("Book now"), array('class' => 'btn-primary buttonBook')); ?>
					<?php endif; ?>	
				</div>
			</div>
		</div>
    </div>

	<div class="globalClear"></div>
	
    <?= $this->clinic->description; ?>
    
</div>