<div id="clinicProfile">

<div class="row">
	
	<div class="left">
		<h1><?= $this->clinic->name; ?></h1>
	    <address>
	        <?= $this->clinic->streetaddress; ?>, <?= $this->clinic->postcode; ?> <?= $this->clinic->city; ?>,
	        <?= $this->clinic->province; ?>
	    </address>
    </div>
        
    <div class="right rating">
        <span class="count">86%</span>
        <big>Rating</big><br/ >
		<small>based on YY reviews</small>
    </div>
    <?= $this->AddToFavorite($this->clinic); ?>

    <div class="globalClear"></div>
    
    <ul class="thumbnails">
        <li class="thumbnail">
            <?= $this->ShowClinicLogo($this->clinic); ?>
        </li>
        <? foreach($this->clinic->photos as $photo): ?>
        <?= $this->ShowPhoto($photo, 'small'); ?>
        <? endforeach; ?>
    </ul>
    
    <div class="hidden" style="position: absolute;" id="image-holder"> </div>
    
    <script>
	    $(document).ready(function() {
	       $(".photo-small").mouseover(function() {
	            var src = $(this).attr("src");
	            var src =src.replace("small", "medium");
	
	            $("#image-holder").removeClass('hidden').html('<img src=' + src + '>');
	       });
	       $(".photo-small").mouseout(function() {
	           $("#image-holder").addClass('hidden');
	       })
	    });
	</script>
    <?php if($this->LoggedUser()->roleName == 'patient'): ?>
        <a id="buttonBook" href="<?= $this->url(array('slug' => $this->clinic->slug), 'newReservation', true);?>" class="btn btn-primary"><?= $this->translate('Book now'); ?></a>
    <?php else: ?>
        <?= $this->LoggedLink("Book now", array('class' => 'btn-primary')); ?>
    <?php endif; ?>

    <?= $this->clinic->description; ?>
    
</div>
<div class="row">
    <h2><?= $this->translate('Promotions'); ?></h2>
    <?= $this->clinic->customPromos; ?>
</div>
<div class="row" id="clinic-grouppromotion">
    <img src="/img/group_promotion.png" />
</div>


<? if (count($this->clinic->services) > 0 ): ?>
<div class="row">
        <form method="post" action="<?= $this->url(array(
            'slug' => $this->clinic->slug,
        ), 'newReservation', true); ?>">
            <h2>Services of <?= $this->clinic->name; ?></h2>

            <table class="table">
                <thead>
                    <tr>
                        <th><?= $this->translate('Service name'); ?>:</th>
                        <th><?= $this->translate('Price range'); ?>:</th>
                        <th><?= $this->translate('Description'); ?>:</th>
                        <th><?= $this->translate('Book'); ?>:</th>
                    </tr>
                </thead>
                <tbody>
                    <? foreach ($this->clinic->services as $service): ?>
                        <tr>
                            <td><span>&bull;</span> &nbsp; <strong><a href="<?= $this->url(array(
                                'id' => $service->id
                            ), 'service', true); ?>"><?= $service->category->name; ?></a></strong></td>
                            <td><?= $service->priceMin; ?> - <?= $service->priceMin; ?> Euro</td>
                            <td><?= $service->description; ?></td>
                            <td><input type="checkbox" name="pre_services[]" value="<?=$service->id; ?>"></td>
                        </tr>
                    <? endforeach; ?>
                </tbody>
            </table>
        <?php if($this->LoggedUser()->roleName == 'patient'): ?>
            <input class="btn-primary" type="submit" value="Book now">
        <?php else: ?>
            <?= $this->LoggedLink("Book now", array('class' => 'btn-primary')); ?>
        <?php endif; ?>
        </form>
</div>
<? endif; ?>

</div>
<script type="text/javascript">
    $(document).ready(function(){
       $("a.ajax-post").click(function() {
           $.post($(this).attr("href"), { format: $(this).attr("data-type") });
       });
    });
</script>