<li class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown">Placówki<b class="caret"></b></a>
    <ul class="dropdown-menu">
        <li><a href="<?= $this->url(array('module' => 'admin', 'action' => 'index', 'controller' => 'clinics')); ?>"><?= $this->translate('Lista placówek'); ?></a></li>
    </ul>
</li>
<li class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown">Kategorie<b class="caret"></b></a>
    <ul class="dropdown-menu">
        <li><a href="<?= $this->url(array('module' => 'admin', 'action' => 'index', 'controller' => 'categories')); ?>"><?= $this->translate('Lista kategorii'); ?></a></li>
    </ul>
</li>
<li class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown"><?= $this->translate('Content'); ?><b class="caret"></b></a>
    <ul class="dropdown-menu">
        <li>
            <a href="<?= $this->url(array('module' => 'admin', 'controller' => 'pages'), 'default',true); ?>">
                <?= $this->translate('List pages'); ?></a>
        </li>
        <li>
            <a href="<?= $this->url(array('module' => 'admin', 'action' => 'save-page',
                'controller' => 'pages'), 'default',true); ?>">
                <?= $this->translate('Add new page'); ?></a>
        </li>
        <li>
            <a href="<?= $this->url(array('module' => 'admin', 'action' => 'index',
                'controller' => 'ads'), 'default',true); ?>">
                <?= $this->translate('Ads management'); ?></a>
        </li>
    </ul>
</li>