<div id="menuFloat">

<p class="navbar-text pull-right">
	<?php if($this->LoggedUser()):?>
            <span class="userPanel">
		<?= $this->translate('Logged in as');?>
        <?= $this->LoggedUser('username'); ?>
        <a class="link" href="<?= $this->url(array(
            'action'        => 'logout', 
            'controller'    => 'index', 
            'module'        => 'patient'), 'default', true); ?>"><?= $this->translate('Log out?');?></a>
            </span>
	<?php endif; ?>
	</p>

<ul>
<li class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown">Placówki<b class="caret"></b></a>
    <ul class="dropdown-menu">
        <li><a href="<?= $this->url(array('module' => 'admin', 'action' => 'index', 'controller' => 'clinics'), 'default', true); ?>"><?= $this->translate('Lista placówek'); ?></a></li>
    </ul>
</li>
    <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown">Pacjenci<b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li><a href="<?= $this->url(array('module' => 'admin', 'action' => 'index', 'controller' => 'patients'), 'default', true); ?>"><?= $this->translate('Lista pacjentów'); ?></a></li>
        </ul>
    </li>
<li class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown">Newsletter<b class="caret"></b></a>
    <ul class="dropdown-menu">
        <li><a href="<?= $this->url(array('module' => 'admin', 'action' => 'export-emails-to-csv', 'controller' => 'newsletter'), 'default', true); ?>">
            <?= $this->translate('Export adresów e-mail do CSV'); ?></a></li>
    </ul>
</li>
<li class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown">Kategorie<b class="caret"></b></a>
    <ul class="dropdown-menu">
        <li><a href="<?= $this->url(array('module' => 'admin', 'action' => 'index', 'controller' => 'categories'), 'default', true); ?>">
            <?= $this->translate('Lista kategorii'); ?></a></li>
    </ul>
</li>
<li class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown"><?= $this->translate('Content'); ?><b class="caret"></b></a>
    <ul class="dropdown-menu">
        <li>
            <a href="<?= $this->url(array('module' => 'admin', 'controller' => 'pages'), 'default',true); ?>">
                <?= $this->translate('List pages'); ?></a>
        </li>
        <li>
            <a href="<?= $this->url(array('module' => 'admin', 'action' => 'save-page',
                'controller' => 'pages'), 'default',true); ?>">
                <?= $this->translate('Add new page'); ?></a>
        </li>
        <li>
            <a href="<?= $this->url(array('module' => 'admin', 'action' => 'index',
                'controller' => 'ads'), 'default',true); ?>">
                <?= $this->translate('Ads management'); ?></a>
        </li>
    </ul>
</li>
</ul>

</div>