<li class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown">Kliniki<b class="caret"></b></a>
    <ul class="dropdown-menu">
        <li><a href="<?= $this->url(array('module' => 'admin', 'action' => 'index', 'controller' => 'clinics')); ?>"><?= $this->translate('Lista klinik'); ?></a></li>
    </ul>
</li>
<li class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown">Kategorie<b class="caret"></b></a>
    <ul class="dropdown-menu">
        <li><a href="<?= $this->url(array('module' => 'admin', 'action' => 'index', 'controller' => 'categories')); ?>"><?= $this->translate('Lista kategorii'); ?></a></li>
    </ul>
</li>