<div id="menuFloat">
<p class="navbar-text pull-right">
	<?php if($this->LoggedUser()):?>
            <span class="userPanel">
		<?= $this->translate('Logged in as');?> <a class="link" href="<?= $this->url(array(
            'module'        => 'clinic',
            'controller'    => 'profile', 
            'action'        => 'index'), 'default', true);?>">
        <?= $this->LoggedUser('username'); ?></a>. 
        <a class="link" href="<?= $this->url(array(
            'action'        => 'logout', 
            'controller'    => 'index', 
            'module'        => 'patient'), 'default', true); ?>"><?= $this->translate('Log out?');?></a>
            </span>
	<?php endif; ?>
	</p>



<ul>
    <li>
        <a href="<?= $this->url(
        array('module' => 'clinic', 'action' => 'index', 'controller' => 'profile'), 'default', true
    ); ?>"><?= $this->translate('Rezerwacje pacjentów'); ?> (<?= $this->LoggedUser()->getNewReservationsCount(); ?>)</a>
    </li>
    <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown">
        <?= $this->translate('Zarządzanie placówką'); ?><b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li><a href="<?= $this->url(
                array('module' => 'clinic', 'action' => 'index', 'controller' => 'services'), 'default', true
            ); ?>"><?= $this->translate('Edytuj usługi placówki'); ?></a></li>
            <li><a href="<?= $this->url(
                array('module' => 'clinic', 'action' => 'edit-group-promotions', 'controller' => 'profile'), 'default', true
            ); ?>"><?= $this->translate('Zarządzaj promocją grupową'); ?></a></li>
            <li><a href="<?= $this->url(
                array('module' => 'clinic', 'action' => 'edit-description', 'controller' => 'profile'), 'default', true
            ); ?>"><?= $this->translate('Edytuj opis placówki'); ?></a></li>
            <li><a href="<?= $this->url(
                array('module' => 'clinic', 'action' => 'edit-address', 'controller' => 'profile'), 'default', true
            ); ?>"><?= $this->translate('Edytuj dane adresowe'); ?></a></li>
            <li><a href="<?= $this->url(
                array('module' => 'clinic', 'action' => 'edit-logo', 'controller' => 'profile'), 'default', true
            ); ?>"><?= $this->translate('Edytuj logo'); ?></a></li>
            <li class="divider"></li>
            <li><a href="<?= $this->url(
                array('module' => 'clinic', 'action' => 'edit-settings', 'controller' => 'profile'), 'default', true
            ); ?>"><?= $this->translate('Edytuj ustawienia'); ?></a></li>
            <li><a href="<?= $this->url(
                array('module' => 'clinic', 'action' => 'change-password', 'controller' => 'profile'), 'default', true
            ); ?>"><?= $this->translate('Edytuj hasło dostępu'); ?></a></li>
            <li class="divider"></li>
            <li>
                <a href="<?= $this->url(
                    array('module' => 'clinic', 'action' => 'profile', 'controller' => 'public',
            'slug' => $this->LoggedUser()->slug), 'default', true); ?>">
                <?= $this->translate('See public profile'); ?></a>
            </li>
        </ul>
    </li>

</ul>

</div>