<?php if ($this->pageCount > 1): ?>
<div class="pagination pagination-centered">
    <ul>
        <!-- Previous page link -->
        <?php if (isset($this->previous)): ?>
        <li><a href="<?php echo $this->url(array('page' => $this->previous), 'default'); ?>">
            &lt; Previous
        </a></li>
        <?php else: ?>
        <li class="disabled"><a class="prev" href="#">&lt; Previous</a></li>
        <?php endif; ?>

        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>
        <?php if ($page != $this->current): ?>
            <li>
                <a href="<?php echo $this->url(array('page' => $page), 'default'); ?>">
                    <?php echo $page; ?>
                </a>
            </li>
            <?php else: ?>
            <li class="active"><a><?php echo $page; ?></a></li>
            <?php endif; ?>
        <?php endforeach; ?>

        <!-- Next page link -->
        <?php if (isset($this->next)): ?>
        <li>
            <a class="next" href="<?php echo $this->url(array('page' => $this->next), 'default'); ?>">
                Next &gt;
            </a>
        </li>
        <?php else: ?>
        <li class="disabled">
            <a href="#">Next &gt;</a>
        </li>
        <?php endif; ?>
    </ul>
</div>
<? else: ?>
<?php endif; ?>