
<div class="column">
	<h3>Copyright</h3>
	&copy; Trendmed Sp. z o.o.<br />
	Copyright 2012<br />
</div>


<div class="column">
	<h3>Trendmed</h3>
	<ul>
		<li>&bull; <a href="<?= $this->url(array('type' => 'feedback'), 'contact', true); ?>">
            <?= $this->translate('Contact us'); ?></a>
        </li>
		<li>&bull; <a href="#">Terms of Use</a></li>
		<li>&bull; <a href="#">Privacy Policy</a></li>
		<li>&bull; <a href="#">Review Policy</a></li>
		<li>&bull; <a href="#">Disclaimer</a></li>
	</ul>
</div>


<div class="column">
	<h3><?= $this->translate('For clinics'); ?></h3>
	<ul>

        <li>&bull; <a href="<?= $this->url(
            array('module'=> 'clinic',
                'action' => 'info',
                'controller' => 'register'), 'default', true);?>"><?= $this->translate('Plans and pricing'); ?></a></li>
        <li>&bull; <a href="<?= $this->url(array(
            'module'=> 'clinic',
            'action' => 'index',
            'controller' => 'register'), 'default', true);?>"><?= $this->translate('Register'); ?></a></li>
        <li>&bull; <a href="<?= $this->url(array(
            'module'=> 'clinic',
            'action' => 'index',
            'controller' => 'index'), 'default', true);?>"><?= $this->translate('Login into panel'); ?></a></li>
	</ul>
</div>


<div class="column columnFacebook">
	<h3><?= $this->translate('Share Trendmed'); ?></h3>
</div>


<div class="globalClear"></div>
