
<div class="column">
	<h3>Copyright</h3>
	&copy; Trendmed Sp. z o.o.<br />
	Copyright 2012<br />
</div>


<div class="column">
	<h3>Trendmed</h3>
	<ul>
		<li>&bull; <a href="<?= $this->url(array('type' => 'feedback'), 'contact', true); ?>">
            <?= $this->translate('Contact us'); ?></a>
        </li>
		<li>&bull; <a href="<?= $this->url(array(
            'action' => 'archive',
            'controller' => 'pages',
            'module' => 'default'
        ), 'default', true); ?>"><?= $this->translate('Articles'); ?></a></li>
		<li>&bull; <a href="<?= $this->url(array(
            'slug' => 'regulamin-dla-pacjentow'
        ), 'page', true);?>"><?= $this->translate('Regulamin dla pacjentów'); ?></a></li>
        <li>&bull; <a href="<?= $this->url(array(
            'slug' => 'regulamin-dla-klinik'
        ), 'page', true);?>"><?= $this->translate('Regulamin dla placówek'); ?></a></li>
        <li>&bull; <a href="<?= $this->url(array(
            'slug' => 'serwis-turystyczny'
        ), 'page', true);?>"><?= $this->translate('Travel service'); ?></a></li>
	</ul>
</div>


<div class="column">
	<h3><?= $this->translate('For clinics'); ?></h3>
	<ul>

        <li>&bull; <a href="<?= $this->url(
            array('module'=> 'clinic',
                'action' => 'info',
                'controller' => 'register'), 'default', true);?>"><?= $this->translate('Plans and pricing'); ?></a></li>
        <li>&bull; <a href="<?= $this->url(array(
            'module'=> 'clinic',
            'action' => 'index',
            'controller' => 'register'), 'default', true);?>"><?= $this->translate('Register'); ?></a></li>
        <li>&bull; <a href="<?= $this->url(array(
            'module'=> 'clinic',
            'action' => 'index',
            'controller' => 'index'), 'default', true);?>"><?= $this->translate('Login into panel'); ?></a></li>
	</ul>
</div>


<div class="column columnFacebook">
	<h3><?= $this->translate('Share Trendmed'); ?></h3>
</div>


<div class="globalClear"></div>
<div id="fb-root"></div>
<script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/pl_PL/all.js#xfbml=1&appId=192773620840368";
    fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>