
<div class="column">
	<h3>Copyright</h3>
	&copy; Trendmed Sp. z o.o.<br />
	Copyright 2012<br />
	&bull; <a href="#">About us</a>
</div>


<div class="column">
	<h3>Trendmed</h3>
	<ul>
		<li>&bull; <a href="#">Terms of Use</a></li>
		<li>&bull; <a href="#">Privacy Policy</a></li>
		<li>&bull; <a href="#">Review Policy</a></li>
		<li>&bull; <a href="#">Disclaimer</a></li>
	</ul>
</div>


<div class="column">
	<h3>Features</h3>
	<ul>
		<li>&bull; <a href="#">Terms of Use</a></li>
		<li>&bull; <a href="#">Privacy Policy</a></li>
		<li>&bull; <a href="#">Review Policy</a></li>
		<li>&bull; <a href="#">Disclaimer</a></li>
	</ul>
</div>


<div class="column">
	<h3>Easy to use</h3>
	<p>
		Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer at 
		sapien lorem. Donec volutpat, risus at ornare.
	</p>
</div>


<div class="column columnFacebook">
	<h3>Share Trendmed</h3>
</div>


<div class="globalClear"></div>

