<div id="fb-root" appid="<?= $this->appId; ?>"></div>

<div class="modal hide fade" id="loginCallToAction">
  <div class="modal-header">
    <button class="close" data-dismiss="modal">×</button>
    <h3><?= $this->translate('Login or create account'); ?></h3>
  </div>
  <div class="modal-body">
      <?= $this->translate('Create free account to use all features on Trendmed.eu!'); ?>
    <? $form = new Patient_Form_Login();
       $form->setReferer($_SERVER['REQUEST_URI']);
       $form->setAction($this->url(array(
           'action' => 'index',
           'controller' => 'index',
           'module' => 'patient',
       ), 'default', true));
       echo $form;
      ?>

  </div>
  <div class="modal-footer">
    <a href="<?= $this->url(
        array(
            'action' => 'index',
            'controller' => 'register',
            'module' => 'patient'
        ), 'default', true
    ); ?>" class="btn btn-primary"><?= $this->translate('Create free account');?></a>
	<button class="btn facebook-login">Login via Facebook</button>
  </div>
</div>
