<div class="navbar navbar-fixed-top" xmlns="http://www.w3.org/1999/html">
    <div class="paski"></div>
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="<?= $this->url(
          array('action' => 'index',
              'controller' => 'index',
              'module' => 'default'), 'default', true); ?>">Trendmed</a>
      <div class="nav-collapse">
        
		<p class="navbar-text pull-right">
		<?php if($this->LoggedUser()):?>
           
		<?php else: ?>
            <a class="login" href="<?= $this->url(array('action' => 'index', 'controller' => 'index', 'module' => 'patient'), 'default', true); ?>"><?= $this->translate('Patient login'); ?></a>
			<a class="register" href="<?= $this->url(array('action' => 'index', 'controller' => 'register', 'module' => 'patient'), 'default', true); ?>"><?= $this->translate('Patient signup'); ?></a>
		<?php endif; ?>
		</p>
                
                
        <ul class="nav">
            <?php foreach($this->GetConfig()->languages as $language): ?>
                <a href="<?= $this->url(array(
                    'lang' => $language->code,
                ),'changeLanguage', true); ?>"><img src="/img/flags/<?= $language->code;?>.png" alt="Change language to: <?= $language->name;?>"></a>
            <?php endforeach; ?>
        </ul>
                
                
      </div><!--/.nav-collapse -->
    </div>
  </div>
    <div class="clear"></div>
</div>