<div id="menuFloat">
	<p class="navbar-text pull-right">
		<?php if($this->LoggedUser()):?>
	            <span class="userPanel">
			<?= $this->translate('Logged in as');?> <a class="link" href="<?= $this->url(array(
	            'module'        => 'patient', 
	            'controller'    => 'profile', 
	            'action'        => 'index'), 'default', true);?>">
	        <?= $this->LoggedUser('username'); ?></a>. 
	        <a class="link" href="<?= $this->url(array(
	            'action'        => 'logout', 
	            'controller'    => 'index', 
	            'module'        => 'patient'), 'default', true); ?>"><?= $this->translate('Log out?');?></a>
	            </span>
		<?php endif; ?>
	</p>

	<ul>
		<li class="dropdown">
		    <a class="dropdown-toggle" data-toggle="dropdown"><?= $this->translate('My account'); ?><b class="caret"></b></a>
		    <ul class="dropdown-menu">
		        <li>
                    <a href="<?= $this->url(
                    array('module' => 'patient', 'action' => 'edit-details', 'controller' => 'profile'),
                    'default', true
                ); ?>"><?= $this->translate('Edit my details'); ?></a>
                </li>
		        <li>
                    <a href="<?= $this->url(
                    array('module' => 'patient', 'action' => 'change-password', 'controller' => 'profile'),
                    'default', true); ?>"><?= $this->translate('Change my password'); ?></a>
                </li>
                <li>
                    <a href="<?= $this->url(
                    array('module' => 'patient', 'action' => 'change-email', 'controller' => 'profile'),
                    'default', true); ?>"><?= $this->translate('Change my e-mail address'); ?></a>
                </li>
		    </ul>
		</li>
		<li class=""><a href="<?= $this->url(array('module' => 'patient', 'action' => 'index', 'controller' => 'profile'), 'default', true); ?>"><?= $this->translate('My reservations'); ?></a></li>
	</ul>
</div>