<div class="modal hide fade" id="share" tabindex="-1" role="dialog" aria-labelledby="myShareForm" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3><?= $this->translate('Recommend this clinic to your friends'); ?></h3>
    </div>
    <form method="post" class="ajax" action="<?= $this->url(array(
        'controller'    => 'index',
        'action'        => 'share-link',
        'module'        => 'default'
    ), 'default', true); ?>">
        <div class="modal-body" id="shareForm">
            <div class="shareFormInput">
                <label for="shareEmail"><?= $this->translate('Your friend e-mail address'); ?></label>
                <input type="email" id="shareEmail" name="shareEmail" value="" required="required" />
                <p class="description">
                    <?= $this->translate('You can type multiply e-mail separating them with comma'); ?>
                </p>
            </div>
            <div class="shareFormInput">
                <label for="shareEmail"><?= $this->translate('Your e-mail address'); ?></label>
                <input type="email" id="myEmail" name="myEmail"  required="required" value="<?= $this->patient ? $this->patient->getEmailaddress() : ''; ?>" />
            </div>
			<div class="row-fluid">
				<div class="span6">
	                <h4><?= $this->translate('Share on facebook'); ?></h4>
	                <div class="fb-like" data-send="false" data-width="200" data-show-faces="true" data-action="recommend"></div>
	            </div>
	            <div class="span6">
	                <h4><?= $this->translate('Share on Twitter'); ?></h4>
	                <a href="https://twitter.com/share" class="twitter-share-button" data-via="trendmed" data-size="large">Tweet</a>
	                <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
	            </div><div class="clearfix"></div>
			</div>
            <div class="clearfix"></div>
        </div>
        <div class="modal-footer">
            <input type="hidden" name="clinic_id" value="<?=$this->clinic->id; ?>">
            <input type="submit" value="<?= $this->translate('Poleć'); ?>" class="btn btn-primary" />
            <button class="btn" data-dismiss="modal" aria-hidden="true"><?= $this->translate('Close'); ?></button>
        </div>
    </form>
</div>
<script type="text/javascript">
    $(document).ready(function() {
       $("form.ajax").bind("submit", function(event) {
           var form = this;
           $.post($(this).attr("action"), $(this).serialize(), function(data) {
               $(form).children("div.modal-body").html(data);
               $(form).find("input[type=submit]").addClass("hidden");
           });
           event.preventDefault();
       });
    });
</script> 