<!-- application/layouts/scripts/layout.phtml -->
<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php echo $this->jQuery(); ?>
<?php echo $this->headMeta(); ?>
<?php echo $this->headLink(); ?>
<?php echo $this->headStyle(); ?>
<?php echo $this->headScript(); ?>
<?php echo $this->headTitle(); ?>
</head>
<body>
    
        <div class="shadow"></div>
        
	<?= $this->render('_navbar.phtml'); ?>
	
	<div class="container">
	      <div class="row-fluid">
	        <div id="sidebar" class="span3 hidden">
	          <div class="well sidebar-nav">
	            <ul class="nav nav-list">
	              <li class="nav-header">Sidebar</li>
	              <li class="active"><a href="#">Link</a></li>
	              <li><a href="#">Link</a></li>
	              <li><a href="#">Link</a></li>
	              <li><a href="#">Link</a></li>
	              <li class="nav-header">Sidebar</li>
	              <li><a href="#">Link</a></li>
	              <li><a href="#">Link</a></li>
	              <li><a href="#">Link</a></li>
	              <li><a href="#">Link</a></li>
	              <li><a href="#">Link</a></li>
	              <li><a href="#">Link</a></li>
	              <li class="nav-header">Sidebar</li>
	              <li><a href="#">Link</a></li>
	              <li><a href="#">Link</a></li>
	              <li><a href="#">Link</a></li>
	            </ul>
	          </div><!--/.well -->
	        </div><!--/span-->
                
                
	        <div id="content" class="span9">
			  <?php echo $this->FlashMessenger(); ?>
		      <?php echo $this->layout()->content ?>
	        </div><!--/span-->
                
                
	      </div><!--/row-->

	      <hr>

	      <footer>
	        <p>2012 &copy; Trendmed Sp. z o.o.</p>
	      </footer>

	    </div><!--/.fluid-container-->
</body>
</html>