<!-- application/layouts/scripts/layout.phtml -->
<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php echo $this->jQuery(); ?>
<?php echo $this->headMeta(); ?>
<?php echo $this->headLink(); ?>
<?php echo $this->headStyle(); ?>
<?php echo $this->headScript(); ?>
<?php echo $this->headTitle(); ?>
</head>
<body>
	
	<?= $this->userMenu(); ?>
	
    <div class="shadow"></div>
        
	<?= $this->render('_navbar.phtml'); ?>
	
	<div class="container">
	      <div class="row-fluid">
	        <div id="sidebar" class="span3">
	          <div class="well sidebar-nav">
	            <ul class="nav nav-list">
                    <?= $this->CategoriesTree($this->selectedCategory); ?>
	            </ul>
	          </div><!--/.well -->
	        </div><!--/span-->
                
                
	        <div id="content" class="span9">
			  <?php echo $this->FlashMessenger(); ?>
		      <?php echo $this->layout()->content ?>
	        </div><!--/span-->
                
                
	      </div><!--/row-->

	      <hr>

	      <footer>
              <?= $this->render('_footer.phtml'); ?>
	      </footer>

	    </div><!--/.fluid-container-->
</body>
</html>