<!-- application/layouts/scripts/layout.phtml -->
<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php echo $this->jQuery(); ?>
<?php echo $this->headMeta(); ?>
<?php echo $this->headLink(); ?>
<?php echo $this->headStyle(); ?>
<?php echo $this->headScript(); ?>
<?php echo $this->headTitle(); ?>
</head>
<body>
    
    <?= $this->userMenu(); ?>
    
    <div class="shadow"></div>
        
    <?= $this->render('_navbar.phtml'); ?>

    <div class="container">
		<div class="page-header">
			<h1><?= $this->translate(strip_tags($this->headTitle()->toString())); ?></h1>
		</div>
		<?php echo $this->FlashMessenger(); ?>
		<?php echo $this->layout()->content ?>

        <hr>
        <footer>
            <?= $this->render('_footer.phtml'); ?>
        </footer>
    </div> <!-- /container -->

</body>
</html>