<p>
    Witamy, <br>
    administrator portalu Trendmed.eu ustanowił nowe hasło dla Państwa placówki: <strong><?= $this->password; ?></strong><br>
    <a href="http://<?= $_SERVER['HTTP_HOST'];?>">Mogą się Państwo teraz zalogować.</a> Sugerujemy zmiane hasła!  <br>
    <br>
    Pozdrawiamy<br>
    Zespół Trendmed<br>
    <br>
    <br>
    Jeśli mają Państwo jakiekolwiek pytania dotyczące funkcjonowania portalu <a href="http://<?= $_SERVER['HTTP_HOST'];?><?= $this->url(array('type' => "feedback"), 'contact'); ?>">zapraszamy do kontaktu</a>. <br>
</p>
</p>