<p>
    Witaj,<br>
    <br>
    <?= $this->translate('Aby ustanowić nowe hasło dla Państwa profilu na portalu Trendmed.eu proszę przejść na niżej podany link lub skopiować
    go całego do przeglądarki:'); ?>
    <br>
    <strong><a href="<?= $this->link;?>" target="_blank"><?= $this->link;?></a></strong><br>
    <br>
    <?= $this->translate('Jeżeli nie używali Państwo funkcji przypomienia hasła do profilu, prosimy o zignorowanietej wiadomości.'); ?><br>
    <br>
    Pozdrawiamy<br>
    Zespół Trendmed<br>
    <br>
    <br>
    Jeśli mają Państwo jakiekolwiek pytania dotyczące funkcjonowania portalu <a href="http://<?= $_SERVER['HTTP_HOST'];?><?= $this->url(array('type' => "feedback"), 'contact'); ?>">zapraszamy do kontaktu</a>. <br>
</p>