<p>
    Witaj,<br>
    <br>
    <?= $this->translate('Aby ustanowić nowe hasło dla Państwa profilu na portalu Trendmed.eu proszę przejść na niżej podany link lub skopiować
    go całego do przeglądarki:'); ?>
    <br>
    <strong><a href="<?= $this->link;?>" target="_blank"><?= $this->link;?></a></strong><br>
    <br>
    <?= $this->translate('Jeżeli nie używali Państwo funkcji przypomienia hasła do profilu, prosimy o zignorowanietej wiadomości.'); ?><br>
</p>
<?= $this->render('clinic/_clinicEmailFooter.phtml'); ?>