<p>
    Witaj,<br>
    <br>
    ten e-mail informuję o zmianie hasła do Twojego konta na profilu <a href="http://www.trendmed.eu">Trendmed.eu</a>.<br>
    <br>
    Jeśli nie zmieniali Państwo hasła do swojego profilu a mimo wszystko otrzymali Państwo niniejszą wiadomość
    <a href="http://<?= $_SERVER['HTTP_HOST'];?><?= $this->url(array('type' => "feedback"), 'contact'); ?>">prosimy o kontakt z administracją</a>.

</p>
<?= $this->render('reservationNotifications/clinic/_clinicEmailFooter.phtml'); ?>