<p>
    Witaj,<br>
    <br>
    ten e-mail informuję o zmianie hasła do Twojego konta na profilu <a href="http://www.trendmed.eu">Trendmed.eu</a>.<br>
    <br>
    Jeśli nie zmieniali Państwo hasła do swojego profilu a mimo wszystko otrzymali Państwo niniejszą wiadomośc <a href="http://<?= $_SERVER['HTTP_HOST'];?><?= $this->url(array('type' => "feedback"), 'contact'); ?>">prosimy o kontakt z administracją</a>.    <br>
    <br>
    Pozdrawiamy<br>
    Zespół Trendmed<br>
    <br>
    Jeśli mają Państwo jakiekolwiek pytania dotyczące funkcjonowania portalu <a href="http://<?= $_SERVER['HTTP_HOST'];?><?= $this->url(array('type' => "feedback"), 'contact'); ?>">zapraszamy do kontaktu</a>. <br>
</p>

