<p>
    Witamy na portalu Trendmed.eu!<br>
    <br>
    Właśnie dokonali Państwo pełnej aktywacji konta. Mogą się Państwo zalogować do swojego profilu i uzupełnić
    dane placówki oraz dodać usługi, które chcieliby Państwo promować na naszym portalu.
    <br>
    Pozdrawiamy<br>
    Zespół Trendmed<br>
    <br>
    <br>
    Jeśli mają Państwo jakiekolwiek pytania dotyczące funkcjonowania portalu <a href="http://<?= $_SERVER['HTTP_HOST'];?><?= $this->url(array('type' => "feedback"), 'contact'); ?>">zapraszamy do kontaktu</a>. <br>
</p>
<?= $this->render('reservationNotifications/clinic/_clinicEmailFooter.phtml'); ?>