<!DOCTYPE html>
<html lang="pl">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" >
    </head>
    <body>
        <p>
            Dzień Dobry,<br>
            dokonalu Państwo udanej rejestracji w portalu Trendmed.eu.
            Jesteśmy wyszukiwarką usług medycznych, kosmetycznych,
            sanatoriów, spa-weelness przeznaczoną głównie dla obcokrajowców.
        </p>
        <p>
            <strong>Prosimy o zamieszczenie swojej oferty w panelu pod adresem:</strong><br>
            <a href="http://www.trendmed.eu/clinic">http://www.trendmed.eu/clinic</a>
        </p>
        <footer>
            Zespół Trendmed
        </footer>
    </body>
</html>
