<div class="alert alert-info">

    Rejestracja jest całkowicie darmowa i zajmie Ci maksymalnie kilka minut.
    <br><br>
    Po rejestracji zaloguj się do panelu zarządzania placówki i dodaj swoją ofertę.
    Sugerujemy wcześniejsze przygotowanie opisu placówki, oferowanych usług w językach: polskim, angielskim, niemieckim, oraz przygotowanie zdjęć placówki , usług.
    Dodawanie oferty jest nieskomplikowane, w przypadku problemów prosimy o mail: <a href="mailto:kontakt@trendmed.eu">kontakt@trendmed.eu</a>
    <br><br>
    Osoba rejestrująca będzie proszona o przesłanie dokumentów rejestrowych placówki oraz potwierdzenie prawa do reprezentowania jej.
</div>
<?= $this->form; ?>