<div class="row-fluid" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
    <div class="span8">
        <p>
            Serwis Trendmed.eu ma na celu gromadzenie i prezentowanie polskich ofert medycznych, kosmetycznych, spa i sanatoriów.
            Kierowany jest głównie do odbiorców zainteresowanych polskimi usługami z Europy Zachodniej.
        </p>
        <h3>Promocja na start:</h3>
        <ul>
            <li>Rejestracja gratis</li>
            <li>3 miesiące promowania oferty gratis</li>
            <li>20 % zniżki dla rocznych umów</li>
            <li>30% zniżki na artykuły sponsorowane w 1 roku działalności portalu</li>
            <li>Abonament po promocji – 450 zł netto/miesięcznie</li>
        </ul>
        <h3>Dlaczego warto? Korzyści:</h3>
        <ul>
            <li>Reklama, prestiż w Polsce</li>
            <li>Reklama, prestiż w Wielkiej Brytanii, Niemczech, krajach Skandynawskich, Danii, Belgii, Holandii, Austrii, Szwajcarii, Norwegii, USA</li>
            <li>Prezentacja Państwa oferty w językach angielskim i niemieckim w Europie Zachodniej</li>
            <li>Możliwość zaprezentowania swoich promocji</li>
            <li>Możliwość wzięcia udziału w promocji grupowej</li>
            <li>Serwis umożliwia dokonanie rezerwacji terminu w Państwa placówce</li>
            <li>Serwis umożliwia pobranie kaucji rezerwacyjnej, jeśli wyrażą Państwo takie życzenie</li>
            <li>Serwis umożliwia pozostawienie komentarza przez klienta po wizycie w Państwa placówce</li>
            -jeśli wyrażą Państwo zgodę na pozostawianie komentarzy</li>
            <li>Serwis umożliwia Państwa klientom zarezerwowanie lotu, hotelu, auta</li>
            <li>Serwis dodatkowo prezentuje pakiet informacji: turystycznych, kulturalnych, rozrywkowych</li>
            <li>Zapewnia dotarcie do ogromnej grupy klientów czy pacjentów</li>
            <li>Zapewnia dostęp do statystyk odwiedzin Państwa oferty na portalu</li>

        </ul>
        <a href="<?= $this->url(array('action' => 'index', 'controller' => 'register', 'module' => 'clinic'), 'default', true); ?>">zarejestruj się teraz  i dodaj swoją ofertę</a>
    </div>
    <span class="span4">
        <img src="/img/skarbonka.png" alt="Trendmed skarbonka" />
    </span>
</div>


