<div class="row-fluid">
    <div class="span8">
        <p>
            W obecnej fazie projektu rejestracja placówki jest <Strong>darmowa</Strong>.
            Wszystkie placówki zarejestrowane przed premierą
            serwisu automatycznie otrzymają darmowy 3 miesięczny abonament.
        </p>
        <h3>Ceny po premierze serwisu</h3>
        <ul>
            <li>abonament miesięczny 450 PLN netto</li>
            <li>pierwsze dwa miesiące GRATIS</li>
            <li>zniżki dla rocznych umów</li>
            <li>30% zniżki na artykuły sponsorowane
                w pierwszym roku</li>
        </ul>

    </div>
    <span class="span4">
        <img src="/img/skarbonka.png" alt="Trendmed skarbonka" />
    </span>
</div>
