<?= $this->element->addressInfo ?><a href="#" rel="tooltip" title="first tooltip">pomoc</a>
<?= $this->element->representantInfo ?><a href="#" rel="tooltip" title="first tooltip">pomoc</a>
<?= $this->element->accountInfo ?><a href="#" rel="tooltip" title="first tooltip">pomoc</a>
<div class="form-actions">
	<?= $this->element->submit ?>
	<a href="<?= $this->url(array('action' => 'index', 'controller' => 'index', 'module' => 'user')); ?>" class="btn"><?= $this->translate('Already have an account?'); ?></a>
</div>
<script>
    $(document).ready(function(){
       $("a[rel=tooltip]").tooltip(); 
    });
</script>