<fieldset>
    <legend>
        <?= $this->translate('Address info'); ?>
    </legend>
    <?= $this->element->type ?>
    <?= $this->element->name ?>
    <?= $this->element->streetaddress ?>
    <?= $this->element->city ?>
    <?= $this->element->postcode ?>
    <?= $this->element->province ?>
</fieldset>
<fieldset>
    <legend>
        <?= $this->translate('Contact person'); ?><a href="#" rel="tooltip" title="Podaj dane osoby kontaktowej,
        która będzie prowadziła sprawy placówki na portalu Trendmed. Podany e-mail będzie zarazem loginem do konta.">i</a>
    </legend>
    <?= $this->element->repName ?>
    <?= $this->element->repEmail ?>
    <?= $this->element->repPhone ?>
</fieldset>
<fieldset>
    <legend>
        <?= $this->translate('Account info'); ?>
    </legend>
    <?= $this->element->password; ?>
    <?= $this->element->password_confirmation; ?>
</fieldset>
<div class="form-actions">
	<?= $this->element->submit ?>
	<a href="<?= $this->url(array('action' => 'index', 'controller' => 'index', 'module' => 'clinic')); ?>" class="btn">
        <?= $this->translate('Already have an account?'); ?></a>
</div>
<script>
    $(document).ready(function(){
       $("a[rel=tooltip]").tooltip(); 
    });
</script>