<p>
    <?= $this->translate('You have to be logged in to perform that action'); ?>.<br>
    <a href="<?= $this->url(array('action' => 'index', 'controller' => 'index', 'module' => 'patient'), 'default', true); ?>"><?= $this->translate('Login'); ?></a>  <?= $this->translate('or'); ?> <a href="<?= $this->url(array('action' => 'index', 'controller' => 'register', 'module' => 'patient'), 'default', true); ?>"><?= $this->translate('register'); ?></a>
</p>