        <div class="alert alert-block alert-notice">
            <?= $this->translate('Opis Twojej placówki oraz zdjęcia będą widoczne na publicznym (widocznym przez
            pacjentów) profilu Twojej placówki. Warto aby był zwięzły i szczery.');?>
        </div>
        <div id="editClinic" class="form-horizontal">
            <?= $this->form; ?>
        </div>

        <br /><br />

        <h3 style="padding:0 0 10px;">Zdjęcia Twojej kliniki</h3>
        <? if( count($this->LoggedUser()->photos) < $this->config->clinics->photo->limit): ?>
            <p><?= $this->translate('Here You can add any photos of Your object, that will be shown on Your public profile'); ?>.</p>
            <div id="photoUpload"><?= $this->photoForm; ?></div>
        <? else: ?>
            <p>Nie możesz dodać więcej zdjęć z uwagi na limit (<?= $this->config->clinics->photo->limit; ?>)</p>
        <? endif;?>
        <? if(count($this->LoggedUser()->photos)>0): ?>
            <ul class="thumbnails">
            <? foreach($this->LoggedUser()->photos as $photo): ?>
                <li class="thumbnail">
                    <?= $this->ShowClinicPhoto($photo, 'medium'); ?>
                    <p class="caption"><a href="<?= $this->url(
                        array(
                            'action' => 'delete-clinic-photo',
                            'controller' => 'profile',
                            'module' => 'clinic',
                            'id'    => $photo->id,
                        )
                    ); ?>" class="btn btn-danger confirm"> <i class="icon-white icon-trash"> </i></a> </p>
                </li>
            <? endforeach; ?>
            </ul>
        <? endif; ?>