<div class="form-horizontal">
    <? if (!$this->clinic->description): ?>
        <div class="alert alert-block">
            <h4 class="alert-heading">Krok 1</h4>
                <a href="<?= $this->url(
                    array(
                        'action'        => 'edit-description',
                        'controller'    => 'profile',
                        'module'        => 'clinic',
                    )
                ); ?>">Uzupełnij opis swojej placówki</a> widoczny dla Twoich potencjalnych pacjentów oraz dodaj zdjęcia.
        </div>
    <? endif;?>
    <? if (count($this->clinic->services) < 1): ?>
        <div class="alert alert-block">
            <h4 class="alert-heading">Krok 2</h4>
            <a href="<?= $this->url(
                array(
                    'action'        => 'edit-services',
                    'controller'    => 'services',
                    'module'        => 'clinic',
                )
            ); ?>">Dodaj usługi</a> swojej placówki, aby być widocznym w naszym katalogu.
        </div>
    <? endif;?>
    <? if (!$this->clinic->logoDir): ?>
        <div class="alert alert-block">
            <h4 class="alert-heading">Krok 3</h4>
            <a href="<?= $this->url(
                array(
                    'action'        => 'edit-logo',
                    'controller'    => 'profile',
                    'module'        => 'clinic',
                )
            ); ?>">Wgraj logo</a> swojej placówki.
        </div>
    <? endif;?>
</div>
<?php if (count($this->reservations) >0 ): ?>
<table class="table">
    <thead>
    <tr>
        <th>
            <?= $this->translate('Date'); ?>
        </th>
        <th>
            <?= $this->translate('Patient'); ?>
        </th>
        <th>
            <?= $this->translate('Services'); ?>
        </th>
        <th>
            <?= $this->translate('Status'); ?>
        </th>
        <th>
            <?= $this->translate('Actions'); ?>
        </th>
    </tr>
    </thead>
    <tbody>
        <?php foreach ($this->reservations as $reservation): ?>
    <tr>
        <td><?= $reservation->created->format("d-m-Y"); ?></td>
        <td><?= $reservation->patient->name; ?></td>
        <td>
            <ul>
                <?php foreach($reservation->services as $service): ?>
                <li><?= $service->category->name; ?></li>
                <?php endforeach; ?>
            </ul>
        </td>
        <td>
            <?php $status =  $reservation->getStatusAsArray(); echo $this->translate($status['name']); ?>
        </td>
        <td>
            put actions over here
        </td>
    </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php endif;?>