<div class="form-horizontal">
    <? if (!$this->clinic->description): ?>
        <div class="alert alert-block">
            <h4 class="alert-heading">Krok 1</h4>
                <a href="<?= $this->url(
                    array(
                        'action'        => 'edit-description',
                        'controller'    => 'profile',
                        'module'        => 'clinic',
                    )
                ); ?>">Uzupełnij opis swojej placówki</a> widoczny dla Twoich potencjalnych pacjentów oraz dodaj zdjęcia.
        </div>
    <? endif;?>
    <? if (count($this->clinic->services) < 1): ?>
        <div class="alert alert-block">
            <h4 class="alert-heading">Krok 2</h4>
            <a href="<?= $this->url(
                array(
                    'action'        => 'edit-services',
                    'controller'    => 'services',
                    'module'        => 'clinic',
                )
            ); ?>">Dodaj usługi</a> swojej placówki, aby być widocznym w naszym katalogu.
        </div>
    <? endif;?>
    <? if (!$this->clinic->logoDir): ?>
        <div class="alert alert-block">
            <h4 class="alert-heading">Krok 3</h4>
            <a href="<?= $this->url(
                array(
                    'action'        => 'edit-logo',
                    'controller'    => 'profile',
                    'module'        => 'clinic',
                )
            ); ?>">Wgraj logo</a> swojej placówki.
        </div>
    <? endif;?>
</div>
<?php if (count($this->reservations) >0 ): ?>
<table class="table reservationList">
    <thead>
    <tr>
        <th>
            <?= $this->translate('Creation date'); ?>
        </th>
        <th>
            <?= $this->translate('Patient'); ?>
        </th>
        <th>
            <?= $this->translate('Services'); ?>
        </th>
        <th>
            <?= $this->translate('Reservation date'); ?>
        </th>
        <th>
            <?= $this->translate('Status'); ?>
        </th>
        <th>
            <?= $this->translate('Actions'); ?>
        </th>
    </tr>
    </thead>
    <tbody>
        <?php foreach ($this->reservations as $reservation): ?>

        <tr<?php if($reservation->getStatus() == 'new'):?> class="new"<?php endif;?>>
                <td><?= $reservation->created->format("d-m-Y"); ?></td>
                <td><?= $reservation->patient->name; ?></td>
                <td>
                    <ul>
                        <?php foreach($reservation->services as $service): ?>
                        <li><?= $service->category->name; ?></li>
                        <?php endforeach; ?>
                    </ul>
                </td>
                <td>
                    Od <?= $reservation->dateFrom->format("d-m-Y"); ?> do <?= $reservation->dateTo->format("d-m-Y"); ?>
                </td>
                <td>
                    <?php $status = $reservation->getStatusAsArray(); echo $this->translate($status['name']); ?>
                </td>
                <td>
                    <div class="btn-group">
                        <a class="btn" href="#reservation-details-<?= $reservation->id;?>" data-toggle="modal"><?= $this->translate('Zobacz szczegóły'); ?></a>
                        <button class="btn dropdown-toggle" data-toggle="dropdown">
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu">
                            <!-- dropdown menu links -->
                            <?php foreach($status['actions']['clinic'] as $action): ?>
                            <li>
                                <a href="<?= $this->url(array('id' => $reservation->id),
                                $this->config->reservation->action->clinic->$action->routeName); ?>">
                                    <?= $this->translate($this->config->reservation->action->clinic->$action->name); ?>
                                </a>
                            </li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                </td>
                <!-- Modal -->
                <div class="modal hide fade" id="reservation-details-<?= $reservation->id;?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                        <h3 id="myModalLabel">Modal header</h3>
                    </div>
                    <div class="modal-body">
                        <?= $this->partial('reservations/_reservationDetails.phtml', array('reservation' => $reservation)); ?>
                    </div>
                    <div class="modal-footer">
                        <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
                        <button class="btn btn-primary">Save changes</button>
                    </div>
                </div>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php endif;?>