<a class="btn" href="<?= $this->url(array('action' => 'index', 'controller' => 'profile', 'module' => 'patient'), 'default', true); ?>">&laquo; lista rezerwacji</a>
<div class="alert alert-block alert-info">
    <?= $this->translate('If you are satisfied by new date of reservation by clinic (see below)
     you can confirm the reservation. Or you can discard this reservation if the date is not
      suitable to you and make new one.'); ?>
</div>
<?= $this->partial('reservations/_reservationDetails.phtml', array('reservation' => $this->reservation)); ?>
    <p>

    </p>
<?= $this->form; ?>