<a class="btn" href="<?= $this->url(array('action' => 'index', 'controller' => 'profile', 'module' => 'patient'), 'default', true); ?>">&laquo; lista rezerwacji</a>
<div class="alert alert-block alert-info">
    <div class="alert alert-block alert-info">
        <?= $this->translate($this->config->reservation->action->patient->cancel->description); ?>
    </div>
</div>
<?= $this->partial('reservations/_reservationDetails.phtml', array('reservation' => $this->reservation)); ?>
    <p>

    </p>
<?= $this->form; ?>