<div class="pay-bill">
	<div class="pay-desc">
		<?php
		    printf(
		        $this->translate("<p>Opłacasz kaucję rejestracyjną w wysokości <strong>%3\$s Euro</strong> za wizytę w placówce %1\$s.<br />Numer rezerwacji to %2\$s. </p><div class='clinic-notice'><p>Po dokonaniu
		płatności placówka zostnie powiadomiona o tym fakcie. <br />Płatność jest wymagana aby rezerwacja była ważna.</p></div>"),
		        $this->reservation->clinic->name,
		        $this->reservation->id,
		        $this->config->clinics->settings->billSize
		    );
		?>
	</div>
		<div class="paypal">
			<form action="https://www.paypal.com/cgi-bin/webscr" method="post">
			    <input type="hidden" name="cmd" value="_s-xclick">
			    <input type="hidden" name="hosted_button_id" value="G6R5FGLBUHTGU">
			    <input type="hidden" name="notify_url" value="http://www.trendmed.eu/index/pay-confirm">
			    <input type="hidden" name="return" value="http://www.trendmed.eu/reservation/<?= $this->reservation->id; ?>/payment/<?= $this->reservation->paymentHash; ?>/ok">

			    <input type="hidden" name="rm" value="2">
			    <input type="hidden" name="item_number" value="<?= $this->reservation->id; ?>">
			    <input type="hidden" name="item_name" value="reservation">
			    <input type="image" src="https://www.paypalobjects.com/en_GB/i/btn/btn_paynowCC_LG.gif" border="0" name="submit" alt="PayPal — The safer, easier way to pay online." id="paypal-submit">
			    <img alt="" border="0" src="https://www.paypalobjects.com/pl_PL/i/scr/pixel.gif" width="1" height="1">
			</form>
		</div>
</div>